/// AUTO GENERATED FILE, DO NOT EDIT.
///
/// Generated by `package:ffigen`.
import 'dart:ffi' as ffi;

/// stdlib.h 头文件在dart的移植.
class CStdlib {
  /// Holds the Dynamic library.
  final ffi.DynamicLibrary _dylib;

  /// The symbols are looked up in [dynamicLibrary].
  CStdlib(ffi.DynamicLibrary dynamicLibrary) : _dylib = dynamicLibrary;

// ffi.Pointer<ffi.NativeFunction<_typedefC_5>> signal(
//   int arg0,
//   ffi.Pointer<ffi.NativeFunction<_typedefC_6>> arg1,
// ) {
// _signal ??= _dylib.lookupFunction<_c_signal,_dart_signal>('signal');
//   return _signal(
//     arg0,
//     arg1,
//   );
// }
// _dart_signal _signal;

  int getpriority(
    int arg0,
    int arg1,
  ) {
    _getpriority ??=
        _dylib.lookupFunction<_c_getpriority, _dart_getpriority>('getpriority');
    return _getpriority(
      arg0,
      arg1,
    );
  }

  _dart_getpriority _getpriority;

  int getiopolicy_np(
    int arg0,
    int arg1,
  ) {
    _getiopolicy_np ??=
        _dylib.lookupFunction<_c_getiopolicy_np, _dart_getiopolicy_np>(
            'getiopolicy_np');
    return _getiopolicy_np(
      arg0,
      arg1,
    );
  }

  _dart_getiopolicy_np _getiopolicy_np;

  int getrlimit(
    int arg0,
    ffi.Pointer<rlimit> arg1,
  ) {
    _getrlimit ??=
        _dylib.lookupFunction<_c_getrlimit, _dart_getrlimit>('getrlimit');
    return _getrlimit(
      arg0,
      arg1,
    );
  }

  _dart_getrlimit _getrlimit;

  int getrusage(
    int arg0,
    ffi.Pointer<rusage> arg1,
  ) {
    _getrusage ??=
        _dylib.lookupFunction<_c_getrusage, _dart_getrusage>('getrusage');
    return _getrusage(
      arg0,
      arg1,
    );
  }

  _dart_getrusage _getrusage;

  int setpriority(
    int arg0,
    int arg1,
    int arg2,
  ) {
    _setpriority ??=
        _dylib.lookupFunction<_c_setpriority, _dart_setpriority>('setpriority');
    return _setpriority(
      arg0,
      arg1,
      arg2,
    );
  }

  _dart_setpriority _setpriority;

  int setiopolicy_np(
    int arg0,
    int arg1,
    int arg2,
  ) {
    _setiopolicy_np ??=
        _dylib.lookupFunction<_c_setiopolicy_np, _dart_setiopolicy_np>(
            'setiopolicy_np');
    return _setiopolicy_np(
      arg0,
      arg1,
      arg2,
    );
  }

  _dart_setiopolicy_np _setiopolicy_np;

  int setrlimit(
    int arg0,
    ffi.Pointer<rlimit> arg1,
  ) {
    _setrlimit ??=
        _dylib.lookupFunction<_c_setrlimit, _dart_setrlimit>('setrlimit');
    return _setrlimit(
      arg0,
      arg1,
    );
  }

  _dart_setrlimit _setrlimit;

  int _OSSwapInt16(
    int _data,
  ) {
    __OSSwapInt16 ??= _dylib
        .lookupFunction<_c__OSSwapInt16, _dart__OSSwapInt16>('_OSSwapInt16');
    return __OSSwapInt16(
      _data,
    );
  }

  _dart__OSSwapInt16 __OSSwapInt16;

  int _OSSwapInt32(
    int _data,
  ) {
    __OSSwapInt32 ??= _dylib
        .lookupFunction<_c__OSSwapInt32, _dart__OSSwapInt32>('_OSSwapInt32');
    return __OSSwapInt32(
      _data,
    );
  }

  _dart__OSSwapInt32 __OSSwapInt32;

  int _OSSwapInt64(
    int _data,
  ) {
    __OSSwapInt64 ??= _dylib
        .lookupFunction<_c__OSSwapInt64, _dart__OSSwapInt64>('_OSSwapInt64');
    return __OSSwapInt64(
      _data,
    );
  }

  _dart__OSSwapInt64 __OSSwapInt64;

  int wait(
    ffi.Pointer<ffi.Int32> arg0,
  ) {
    _wait ??= _dylib.lookupFunction<_c_wait, _dart_wait>('wait');
    return _wait(
      arg0,
    );
  }

  _dart_wait _wait;

  int waitpid(
    int arg0,
    ffi.Pointer<ffi.Int32> arg1,
    int arg2,
  ) {
    _waitpid ??= _dylib.lookupFunction<_c_waitpid, _dart_waitpid>('waitpid');
    return _waitpid(
      arg0,
      arg1,
      arg2,
    );
  }

  _dart_waitpid _waitpid;

  int waitid(
    int arg0,
    int arg1,
    ffi.Pointer<__siginfo> arg2,
    int arg3,
  ) {
    _waitid ??= _dylib.lookupFunction<_c_waitid, _dart_waitid>('waitid');
    return _waitid(
      arg0,
      arg1,
      arg2,
      arg3,
    );
  }

  _dart_waitid _waitid;

  int wait3(
    ffi.Pointer<ffi.Int32> arg0,
    int arg1,
    ffi.Pointer<rusage> arg2,
  ) {
    _wait3 ??= _dylib.lookupFunction<_c_wait3, _dart_wait3>('wait3');
    return _wait3(
      arg0,
      arg1,
      arg2,
    );
  }

  _dart_wait3 _wait3;

  int wait4(
    int arg0,
    ffi.Pointer<ffi.Int32> arg1,
    int arg2,
    ffi.Pointer<rusage> arg3,
  ) {
    _wait4 ??= _dylib.lookupFunction<_c_wait4, _dart_wait4>('wait4');
    return _wait4(
      arg0,
      arg1,
      arg2,
      arg3,
    );
  }

  _dart_wait4 _wait4;

  ffi.Pointer<ffi.Void> alloca(
    int arg0,
  ) {
    _alloca ??= _dylib.lookupFunction<_c_alloca, _dart_alloca>('alloca');
    return _alloca(
      arg0,
    );
  }

  _dart_alloca _alloca;

  ffi.Pointer<ffi.Void> malloc(
    int __size,
  ) {
    _malloc ??= _dylib.lookupFunction<_c_malloc, _dart_malloc>('malloc');
    return _malloc(
      __size,
    );
  }

  _dart_malloc _malloc;

  ffi.Pointer<ffi.Void> calloc(
    int __count,
    int __size,
  ) {
    _calloc ??= _dylib.lookupFunction<_c_calloc, _dart_calloc>('calloc');
    return _calloc(
      __count,
      __size,
    );
  }

  _dart_calloc _calloc;

  void free(
    ffi.Pointer<ffi.Void> arg0,
  ) {
    _free ??= _dylib.lookupFunction<_c_free, _dart_free>('free');
    return _free(
      arg0,
    );
  }

  _dart_free _free;

  ffi.Pointer<ffi.Void> realloc(
    ffi.Pointer<ffi.Void> __ptr,
    int __size,
  ) {
    _realloc ??= _dylib.lookupFunction<_c_realloc, _dart_realloc>('realloc');
    return _realloc(
      __ptr,
      __size,
    );
  }

  _dart_realloc _realloc;

  ffi.Pointer<ffi.Void> valloc(
    int arg0,
  ) {
    _valloc ??= _dylib.lookupFunction<_c_valloc, _dart_valloc>('valloc');
    return _valloc(
      arg0,
    );
  }

  _dart_valloc _valloc;

  ffi.Pointer<ffi.Void> aligned_alloc(
    int __alignment,
    int __size,
  ) {
    _aligned_alloc ??= _dylib
        .lookupFunction<_c_aligned_alloc, _dart_aligned_alloc>('aligned_alloc');
    return _aligned_alloc(
      __alignment,
      __size,
    );
  }

  _dart_aligned_alloc _aligned_alloc;

  int posix_memalign(
    ffi.Pointer<ffi.Pointer<ffi.Void>> __memptr,
    int __alignment,
    int __size,
  ) {
    _posix_memalign ??=
        _dylib.lookupFunction<_c_posix_memalign, _dart_posix_memalign>(
            'posix_memalign');
    return _posix_memalign(
      __memptr,
      __alignment,
      __size,
    );
  }

  _dart_posix_memalign _posix_memalign;

  void abort() {
    _abort ??= _dylib.lookupFunction<_c_abort, _dart_abort>('abort');
    return _abort();
  }

  _dart_abort _abort;

  int abs(
    int arg0,
  ) {
    _abs ??= _dylib.lookupFunction<_c_abs, _dart_abs>('abs');
    return _abs(
      arg0,
    );
  }

  _dart_abs _abs;

  int atexit(
    ffi.Pointer<ffi.NativeFunction<_typedefC_7>> arg0,
  ) {
    _atexit ??= _dylib.lookupFunction<_c_atexit, _dart_atexit>('atexit');
    return _atexit(
      arg0,
    );
  }

  _dart_atexit _atexit;

  double atof(
    ffi.Pointer<ffi.Int8> arg0,
  ) {
    _atof ??= _dylib.lookupFunction<_c_atof, _dart_atof>('atof');
    return _atof(
      arg0,
    );
  }

  _dart_atof _atof;

  int atoi(
    ffi.Pointer<ffi.Int8> arg0,
  ) {
    _atoi ??= _dylib.lookupFunction<_c_atoi, _dart_atoi>('atoi');
    return _atoi(
      arg0,
    );
  }

  _dart_atoi _atoi;

  int atol(
    ffi.Pointer<ffi.Int8> arg0,
  ) {
    _atol ??= _dylib.lookupFunction<_c_atol, _dart_atol>('atol');
    return _atol(
      arg0,
    );
  }

  _dart_atol _atol;

  int atoll(
    ffi.Pointer<ffi.Int8> arg0,
  ) {
    _atoll ??= _dylib.lookupFunction<_c_atoll, _dart_atoll>('atoll');
    return _atoll(
      arg0,
    );
  }

  _dart_atoll _atoll;

  ffi.Pointer<ffi.Void> bsearch(
    ffi.Pointer<ffi.Void> __key,
    ffi.Pointer<ffi.Void> __base,
    int __nel,
    int __width,
    ffi.Pointer<ffi.NativeFunction<_typedefC_8>> __compar,
  ) {
    _bsearch ??= _dylib.lookupFunction<_c_bsearch, _dart_bsearch>('bsearch');
    return _bsearch(
      __key,
      __base,
      __nel,
      __width,
      __compar,
    );
  }

  _dart_bsearch _bsearch;

  void exit(
    int arg0,
  ) {
    _exit ??= _dylib.lookupFunction<_c_exit, _dart_exit>('exit');
    return _exit(
      arg0,
    );
  }

  _dart_exit _exit;

  ffi.Pointer<ffi.Int8> getenv(
    ffi.Pointer<ffi.Int8> arg0,
  ) {
    _getenv ??= _dylib.lookupFunction<_c_getenv, _dart_getenv>('getenv');
    return _getenv(
      arg0,
    );
  }

  _dart_getenv _getenv;

  int labs(
    int arg0,
  ) {
    _labs ??= _dylib.lookupFunction<_c_labs, _dart_labs>('labs');
    return _labs(
      arg0,
    );
  }

  _dart_labs _labs;

  int llabs(
    int arg0,
  ) {
    _llabs ??= _dylib.lookupFunction<_c_llabs, _dart_llabs>('llabs');
    return _llabs(
      arg0,
    );
  }

  _dart_llabs _llabs;

  int mblen(
    ffi.Pointer<ffi.Int8> __s,
    int __n,
  ) {
    _mblen ??= _dylib.lookupFunction<_c_mblen, _dart_mblen>('mblen');
    return _mblen(
      __s,
      __n,
    );
  }

  _dart_mblen _mblen;

  int mbstowcs(
    ffi.Pointer<ffi.Int32> arg0,
    ffi.Pointer<ffi.Int8> arg1,
    int arg2,
  ) {
    _mbstowcs ??=
        _dylib.lookupFunction<_c_mbstowcs, _dart_mbstowcs>('mbstowcs');
    return _mbstowcs(
      arg0,
      arg1,
      arg2,
    );
  }

  _dart_mbstowcs _mbstowcs;

  int mbtowc(
    ffi.Pointer<ffi.Int32> arg0,
    ffi.Pointer<ffi.Int8> arg1,
    int arg2,
  ) {
    _mbtowc ??= _dylib.lookupFunction<_c_mbtowc, _dart_mbtowc>('mbtowc');
    return _mbtowc(
      arg0,
      arg1,
      arg2,
    );
  }

  _dart_mbtowc _mbtowc;

  void qsort(
    ffi.Pointer<ffi.Void> __base,
    int __nel,
    int __width,
    ffi.Pointer<ffi.NativeFunction<_typedefC_9>> __compar,
  ) {
    _qsort ??= _dylib.lookupFunction<_c_qsort, _dart_qsort>('qsort');
    return _qsort(
      __base,
      __nel,
      __width,
      __compar,
    );
  }

  _dart_qsort _qsort;

  int rand() {
    _rand ??= _dylib.lookupFunction<_c_rand, _dart_rand>('rand');
    return _rand();
  }

  _dart_rand _rand;

  void srand(
    int arg0,
  ) {
    _srand ??= _dylib.lookupFunction<_c_srand, _dart_srand>('srand');
    return _srand(
      arg0,
    );
  }

  _dart_srand _srand;

  double strtod(
    ffi.Pointer<ffi.Int8> arg0,
    ffi.Pointer<ffi.Pointer<ffi.Int8>> arg1,
  ) {
    _strtod ??= _dylib.lookupFunction<_c_strtod, _dart_strtod>('strtod');
    return _strtod(
      arg0,
      arg1,
    );
  }

  _dart_strtod _strtod;

  double strtof(
    ffi.Pointer<ffi.Int8> arg0,
    ffi.Pointer<ffi.Pointer<ffi.Int8>> arg1,
  ) {
    _strtof ??= _dylib.lookupFunction<_c_strtof, _dart_strtof>('strtof');
    return _strtof(
      arg0,
      arg1,
    );
  }

  _dart_strtof _strtof;

  int strtol(
    ffi.Pointer<ffi.Int8> __str,
    ffi.Pointer<ffi.Pointer<ffi.Int8>> __endptr,
    int __base,
  ) {
    _strtol ??= _dylib.lookupFunction<_c_strtol, _dart_strtol>('strtol');
    return _strtol(
      __str,
      __endptr,
      __base,
    );
  }

  _dart_strtol _strtol;

  int strtoll(
    ffi.Pointer<ffi.Int8> __str,
    ffi.Pointer<ffi.Pointer<ffi.Int8>> __endptr,
    int __base,
  ) {
    _strtoll ??= _dylib.lookupFunction<_c_strtoll, _dart_strtoll>('strtoll');
    return _strtoll(
      __str,
      __endptr,
      __base,
    );
  }

  _dart_strtoll _strtoll;

  int strtoul(
    ffi.Pointer<ffi.Int8> __str,
    ffi.Pointer<ffi.Pointer<ffi.Int8>> __endptr,
    int __base,
  ) {
    _strtoul ??= _dylib.lookupFunction<_c_strtoul, _dart_strtoul>('strtoul');
    return _strtoul(
      __str,
      __endptr,
      __base,
    );
  }

  _dart_strtoul _strtoul;

  int strtoull(
    ffi.Pointer<ffi.Int8> __str,
    ffi.Pointer<ffi.Pointer<ffi.Int8>> __endptr,
    int __base,
  ) {
    _strtoull ??=
        _dylib.lookupFunction<_c_strtoull, _dart_strtoull>('strtoull');
    return _strtoull(
      __str,
      __endptr,
      __base,
    );
  }

  _dart_strtoull _strtoull;

  int system(
    ffi.Pointer<ffi.Int8> arg0,
  ) {
    _system ??= _dylib.lookupFunction<_c_system, _dart_system>('system');
    return _system(
      arg0,
    );
  }

  _dart_system _system;

  int wcstombs(
    ffi.Pointer<ffi.Int8> arg0,
    ffi.Pointer<ffi.Int32> arg1,
    int arg2,
  ) {
    _wcstombs ??=
        _dylib.lookupFunction<_c_wcstombs, _dart_wcstombs>('wcstombs');
    return _wcstombs(
      arg0,
      arg1,
      arg2,
    );
  }

  _dart_wcstombs _wcstombs;

  int wctomb(
    ffi.Pointer<ffi.Int8> arg0,
    int arg1,
  ) {
    _wctomb ??= _dylib.lookupFunction<_c_wctomb, _dart_wctomb>('wctomb');
    return _wctomb(
      arg0,
      arg1,
    );
  }

  _dart_wctomb _wctomb;

  void _Exit(
    int arg0,
  ) {
    __Exit ??= _dylib.lookupFunction<_c__Exit, _dart__Exit>('_Exit');
    return __Exit(
      arg0,
    );
  }

  _dart__Exit __Exit;

  int a64l(
    ffi.Pointer<ffi.Int8> arg0,
  ) {
    _a64l ??= _dylib.lookupFunction<_c_a64l, _dart_a64l>('a64l');
    return _a64l(
      arg0,
    );
  }

  _dart_a64l _a64l;

  double drand48() {
    _drand48 ??= _dylib.lookupFunction<_c_drand48, _dart_drand48>('drand48');
    return _drand48();
  }

  _dart_drand48 _drand48;

  ffi.Pointer<ffi.Int8> ecvt(
    double arg0,
    int arg1,
    ffi.Pointer<ffi.Int32> arg2,
    ffi.Pointer<ffi.Int32> arg3,
  ) {
    _ecvt ??= _dylib.lookupFunction<_c_ecvt, _dart_ecvt>('ecvt');
    return _ecvt(
      arg0,
      arg1,
      arg2,
      arg3,
    );
  }

  _dart_ecvt _ecvt;

  double erand48(
    ffi.Pointer<ffi.Uint16> arg0,
  ) {
    _erand48 ??= _dylib.lookupFunction<_c_erand48, _dart_erand48>('erand48');
    return _erand48(
      arg0,
    );
  }

  _dart_erand48 _erand48;

  ffi.Pointer<ffi.Int8> fcvt(
    double arg0,
    int arg1,
    ffi.Pointer<ffi.Int32> arg2,
    ffi.Pointer<ffi.Int32> arg3,
  ) {
    _fcvt ??= _dylib.lookupFunction<_c_fcvt, _dart_fcvt>('fcvt');
    return _fcvt(
      arg0,
      arg1,
      arg2,
      arg3,
    );
  }

  _dart_fcvt _fcvt;

  ffi.Pointer<ffi.Int8> gcvt(
    double arg0,
    int arg1,
    ffi.Pointer<ffi.Int8> arg2,
  ) {
    _gcvt ??= _dylib.lookupFunction<_c_gcvt, _dart_gcvt>('gcvt');
    return _gcvt(
      arg0,
      arg1,
      arg2,
    );
  }

  _dart_gcvt _gcvt;

  int getsubopt(
    ffi.Pointer<ffi.Pointer<ffi.Int8>> arg0,
    ffi.Pointer<ffi.Pointer<ffi.Int8>> arg1,
    ffi.Pointer<ffi.Pointer<ffi.Int8>> arg2,
  ) {
    _getsubopt ??=
        _dylib.lookupFunction<_c_getsubopt, _dart_getsubopt>('getsubopt');
    return _getsubopt(
      arg0,
      arg1,
      arg2,
    );
  }

  _dart_getsubopt _getsubopt;

  int grantpt(
    int arg0,
  ) {
    _grantpt ??= _dylib.lookupFunction<_c_grantpt, _dart_grantpt>('grantpt');
    return _grantpt(
      arg0,
    );
  }

  _dart_grantpt _grantpt;

  ffi.Pointer<ffi.Int8> initstate(
    int arg0,
    ffi.Pointer<ffi.Int8> arg1,
    int arg2,
  ) {
    _initstate ??=
        _dylib.lookupFunction<_c_initstate, _dart_initstate>('initstate');
    return _initstate(
      arg0,
      arg1,
      arg2,
    );
  }

  _dart_initstate _initstate;

  int jrand48(
    ffi.Pointer<ffi.Uint16> arg0,
  ) {
    _jrand48 ??= _dylib.lookupFunction<_c_jrand48, _dart_jrand48>('jrand48');
    return _jrand48(
      arg0,
    );
  }

  _dart_jrand48 _jrand48;

  ffi.Pointer<ffi.Int8> l64a(
    int arg0,
  ) {
    _l64a ??= _dylib.lookupFunction<_c_l64a, _dart_l64a>('l64a');
    return _l64a(
      arg0,
    );
  }

  _dart_l64a _l64a;

  void lcong48(
    ffi.Pointer<ffi.Uint16> arg0,
  ) {
    _lcong48 ??= _dylib.lookupFunction<_c_lcong48, _dart_lcong48>('lcong48');
    return _lcong48(
      arg0,
    );
  }

  _dart_lcong48 _lcong48;

  int lrand48() {
    _lrand48 ??= _dylib.lookupFunction<_c_lrand48, _dart_lrand48>('lrand48');
    return _lrand48();
  }

  _dart_lrand48 _lrand48;

  ffi.Pointer<ffi.Int8> mktemp(
    ffi.Pointer<ffi.Int8> arg0,
  ) {
    _mktemp ??= _dylib.lookupFunction<_c_mktemp, _dart_mktemp>('mktemp');
    return _mktemp(
      arg0,
    );
  }

  _dart_mktemp _mktemp;

  int mkstemp(
    ffi.Pointer<ffi.Int8> arg0,
  ) {
    _mkstemp ??= _dylib.lookupFunction<_c_mkstemp, _dart_mkstemp>('mkstemp');
    return _mkstemp(
      arg0,
    );
  }

  _dart_mkstemp _mkstemp;

  int mrand48() {
    _mrand48 ??= _dylib.lookupFunction<_c_mrand48, _dart_mrand48>('mrand48');
    return _mrand48();
  }

  _dart_mrand48 _mrand48;

  int nrand48(
    ffi.Pointer<ffi.Uint16> arg0,
  ) {
    _nrand48 ??= _dylib.lookupFunction<_c_nrand48, _dart_nrand48>('nrand48');
    return _nrand48(
      arg0,
    );
  }

  _dart_nrand48 _nrand48;

  int posix_openpt(
    int arg0,
  ) {
    _posix_openpt ??= _dylib
        .lookupFunction<_c_posix_openpt, _dart_posix_openpt>('posix_openpt');
    return _posix_openpt(
      arg0,
    );
  }

  _dart_posix_openpt _posix_openpt;

  ffi.Pointer<ffi.Int8> ptsname(
    int arg0,
  ) {
    _ptsname ??= _dylib.lookupFunction<_c_ptsname, _dart_ptsname>('ptsname');
    return _ptsname(
      arg0,
    );
  }

  _dart_ptsname _ptsname;

  int ptsname_r(
    int fildes,
    ffi.Pointer<ffi.Int8> buffer,
    int buflen,
  ) {
    _ptsname_r ??=
        _dylib.lookupFunction<_c_ptsname_r, _dart_ptsname_r>('ptsname_r');
    return _ptsname_r(
      fildes,
      buffer,
      buflen,
    );
  }

  _dart_ptsname_r _ptsname_r;

  int putenv(
    ffi.Pointer<ffi.Int8> arg0,
  ) {
    _putenv ??= _dylib.lookupFunction<_c_putenv, _dart_putenv>('putenv');
    return _putenv(
      arg0,
    );
  }

  _dart_putenv _putenv;

  int random() {
    _random ??= _dylib.lookupFunction<_c_random, _dart_random>('random');
    return _random();
  }

  _dart_random _random;

  int rand_r(
    ffi.Pointer<ffi.Uint32> arg0,
  ) {
    _rand_r ??= _dylib.lookupFunction<_c_rand_r, _dart_rand_r>('rand_r');
    return _rand_r(
      arg0,
    );
  }

  _dart_rand_r _rand_r;

  ffi.Pointer<ffi.Int8> realpath(
    ffi.Pointer<ffi.Int8> arg0,
    ffi.Pointer<ffi.Int8> arg1,
  ) {
    _realpath ??=
        _dylib.lookupFunction<_c_realpath, _dart_realpath>('realpath');
    return _realpath(
      arg0,
      arg1,
    );
  }

  _dart_realpath _realpath;

  ffi.Pointer<ffi.Uint16> seed48(
    ffi.Pointer<ffi.Uint16> arg0,
  ) {
    _seed48 ??= _dylib.lookupFunction<_c_seed48, _dart_seed48>('seed48');
    return _seed48(
      arg0,
    );
  }

  _dart_seed48 _seed48;

  int setenv(
    ffi.Pointer<ffi.Int8> __name,
    ffi.Pointer<ffi.Int8> __value,
    int __overwrite,
  ) {
    _setenv ??= _dylib.lookupFunction<_c_setenv, _dart_setenv>('setenv');
    return _setenv(
      __name,
      __value,
      __overwrite,
    );
  }

  _dart_setenv _setenv;

  void setkey(
    ffi.Pointer<ffi.Int8> arg0,
  ) {
    _setkey ??= _dylib.lookupFunction<_c_setkey, _dart_setkey>('setkey');
    return _setkey(
      arg0,
    );
  }

  _dart_setkey _setkey;

  ffi.Pointer<ffi.Int8> setstate(
    ffi.Pointer<ffi.Int8> arg0,
  ) {
    _setstate ??=
        _dylib.lookupFunction<_c_setstate, _dart_setstate>('setstate');
    return _setstate(
      arg0,
    );
  }

  _dart_setstate _setstate;

  void srand48(
    int arg0,
  ) {
    _srand48 ??= _dylib.lookupFunction<_c_srand48, _dart_srand48>('srand48');
    return _srand48(
      arg0,
    );
  }

  _dart_srand48 _srand48;

  void srandom(
    int arg0,
  ) {
    _srandom ??= _dylib.lookupFunction<_c_srandom, _dart_srandom>('srandom');
    return _srandom(
      arg0,
    );
  }

  _dart_srandom _srandom;

  int unlockpt(
    int arg0,
  ) {
    _unlockpt ??=
        _dylib.lookupFunction<_c_unlockpt, _dart_unlockpt>('unlockpt');
    return _unlockpt(
      arg0,
    );
  }

  _dart_unlockpt _unlockpt;

  int unsetenv(
    ffi.Pointer<ffi.Int8> arg0,
  ) {
    _unsetenv ??=
        _dylib.lookupFunction<_c_unsetenv, _dart_unsetenv>('unsetenv');
    return _unsetenv(
      arg0,
    );
  }

  _dart_unsetenv _unsetenv;

  int arc4random() {
    _arc4random ??=
        _dylib.lookupFunction<_c_arc4random, _dart_arc4random>('arc4random');
    return _arc4random();
  }

  _dart_arc4random _arc4random;

  void arc4random_addrandom(
    ffi.Pointer<ffi.Uint8> arg0,
    int arg1,
  ) {
    _arc4random_addrandom ??= _dylib.lookupFunction<_c_arc4random_addrandom,
        _dart_arc4random_addrandom>('arc4random_addrandom');
    return _arc4random_addrandom(
      arg0,
      arg1,
    );
  }

  _dart_arc4random_addrandom _arc4random_addrandom;

  void arc4random_buf(
    ffi.Pointer<ffi.Void> __buf,
    int __nbytes,
  ) {
    _arc4random_buf ??=
        _dylib.lookupFunction<_c_arc4random_buf, _dart_arc4random_buf>(
            'arc4random_buf');
    return _arc4random_buf(
      __buf,
      __nbytes,
    );
  }

  _dart_arc4random_buf _arc4random_buf;

  void arc4random_stir() {
    _arc4random_stir ??=
        _dylib.lookupFunction<_c_arc4random_stir, _dart_arc4random_stir>(
            'arc4random_stir');
    return _arc4random_stir();
  }

  _dart_arc4random_stir _arc4random_stir;

  int arc4random_uniform(
    int __upper_bound,
  ) {
    _arc4random_uniform ??=
        _dylib.lookupFunction<_c_arc4random_uniform, _dart_arc4random_uniform>(
            'arc4random_uniform');
    return _arc4random_uniform(
      __upper_bound,
    );
  }

  _dart_arc4random_uniform _arc4random_uniform;

  ffi.Pointer<ffi.Int8> cgetcap(
    ffi.Pointer<ffi.Int8> arg0,
    ffi.Pointer<ffi.Int8> arg1,
    int arg2,
  ) {
    _cgetcap ??= _dylib.lookupFunction<_c_cgetcap, _dart_cgetcap>('cgetcap');
    return _cgetcap(
      arg0,
      arg1,
      arg2,
    );
  }

  _dart_cgetcap _cgetcap;

  int cgetclose() {
    _cgetclose ??=
        _dylib.lookupFunction<_c_cgetclose, _dart_cgetclose>('cgetclose');
    return _cgetclose();
  }

  _dart_cgetclose _cgetclose;

  int cgetent(
    ffi.Pointer<ffi.Pointer<ffi.Int8>> arg0,
    ffi.Pointer<ffi.Pointer<ffi.Int8>> arg1,
    ffi.Pointer<ffi.Int8> arg2,
  ) {
    _cgetent ??= _dylib.lookupFunction<_c_cgetent, _dart_cgetent>('cgetent');
    return _cgetent(
      arg0,
      arg1,
      arg2,
    );
  }

  _dart_cgetent _cgetent;

  int cgetfirst(
    ffi.Pointer<ffi.Pointer<ffi.Int8>> arg0,
    ffi.Pointer<ffi.Pointer<ffi.Int8>> arg1,
  ) {
    _cgetfirst ??=
        _dylib.lookupFunction<_c_cgetfirst, _dart_cgetfirst>('cgetfirst');
    return _cgetfirst(
      arg0,
      arg1,
    );
  }

  _dart_cgetfirst _cgetfirst;

  int cgetmatch(
    ffi.Pointer<ffi.Int8> arg0,
    ffi.Pointer<ffi.Int8> arg1,
  ) {
    _cgetmatch ??=
        _dylib.lookupFunction<_c_cgetmatch, _dart_cgetmatch>('cgetmatch');
    return _cgetmatch(
      arg0,
      arg1,
    );
  }

  _dart_cgetmatch _cgetmatch;

  int cgetnext(
    ffi.Pointer<ffi.Pointer<ffi.Int8>> arg0,
    ffi.Pointer<ffi.Pointer<ffi.Int8>> arg1,
  ) {
    _cgetnext ??=
        _dylib.lookupFunction<_c_cgetnext, _dart_cgetnext>('cgetnext');
    return _cgetnext(
      arg0,
      arg1,
    );
  }

  _dart_cgetnext _cgetnext;

  int cgetnum(
    ffi.Pointer<ffi.Int8> arg0,
    ffi.Pointer<ffi.Int8> arg1,
    ffi.Pointer<ffi.Int64> arg2,
  ) {
    _cgetnum ??= _dylib.lookupFunction<_c_cgetnum, _dart_cgetnum>('cgetnum');
    return _cgetnum(
      arg0,
      arg1,
      arg2,
    );
  }

  _dart_cgetnum _cgetnum;

  int cgetset(
    ffi.Pointer<ffi.Int8> arg0,
  ) {
    _cgetset ??= _dylib.lookupFunction<_c_cgetset, _dart_cgetset>('cgetset');
    return _cgetset(
      arg0,
    );
  }

  _dart_cgetset _cgetset;

  int cgetstr(
    ffi.Pointer<ffi.Int8> arg0,
    ffi.Pointer<ffi.Int8> arg1,
    ffi.Pointer<ffi.Pointer<ffi.Int8>> arg2,
  ) {
    _cgetstr ??= _dylib.lookupFunction<_c_cgetstr, _dart_cgetstr>('cgetstr');
    return _cgetstr(
      arg0,
      arg1,
      arg2,
    );
  }

  _dart_cgetstr _cgetstr;

  int cgetustr(
    ffi.Pointer<ffi.Int8> arg0,
    ffi.Pointer<ffi.Int8> arg1,
    ffi.Pointer<ffi.Pointer<ffi.Int8>> arg2,
  ) {
    _cgetustr ??=
        _dylib.lookupFunction<_c_cgetustr, _dart_cgetustr>('cgetustr');
    return _cgetustr(
      arg0,
      arg1,
      arg2,
    );
  }

  _dart_cgetustr _cgetustr;

  int daemon(
    int arg0,
    int arg1,
  ) {
    _daemon ??= _dylib.lookupFunction<_c_daemon, _dart_daemon>('daemon');
    return _daemon(
      arg0,
      arg1,
    );
  }

  _dart_daemon _daemon;

  ffi.Pointer<ffi.Int8> devname(
    int arg0,
    int arg1,
  ) {
    _devname ??= _dylib.lookupFunction<_c_devname, _dart_devname>('devname');
    return _devname(
      arg0,
      arg1,
    );
  }

  _dart_devname _devname;

  ffi.Pointer<ffi.Int8> devname_r(
    int arg0,
    int arg1,
    ffi.Pointer<ffi.Int8> buf,
    int len,
  ) {
    _devname_r ??=
        _dylib.lookupFunction<_c_devname_r, _dart_devname_r>('devname_r');
    return _devname_r(
      arg0,
      arg1,
      buf,
      len,
    );
  }

  _dart_devname_r _devname_r;

  ffi.Pointer<ffi.Int8> getbsize(
    ffi.Pointer<ffi.Int32> arg0,
    ffi.Pointer<ffi.Int64> arg1,
  ) {
    _getbsize ??=
        _dylib.lookupFunction<_c_getbsize, _dart_getbsize>('getbsize');
    return _getbsize(
      arg0,
      arg1,
    );
  }

  _dart_getbsize _getbsize;

  int getloadavg(
    ffi.Pointer<ffi.Double> arg0,
    int arg1,
  ) {
    _getloadavg ??=
        _dylib.lookupFunction<_c_getloadavg, _dart_getloadavg>('getloadavg');
    return _getloadavg(
      arg0,
      arg1,
    );
  }

  _dart_getloadavg _getloadavg;

  ffi.Pointer<ffi.Int8> getprogname() {
    _getprogname ??=
        _dylib.lookupFunction<_c_getprogname, _dart_getprogname>('getprogname');
    return _getprogname();
  }

  _dart_getprogname _getprogname;

  void setprogname(
    ffi.Pointer<ffi.Int8> arg0,
  ) {
    _setprogname ??=
        _dylib.lookupFunction<_c_setprogname, _dart_setprogname>('setprogname');
    return _setprogname(
      arg0,
    );
  }

  _dart_setprogname _setprogname;

  int heapsort(
    ffi.Pointer<ffi.Void> __base,
    int __nel,
    int __width,
    ffi.Pointer<ffi.NativeFunction<_typedefC_10>> __compar,
  ) {
    _heapsort ??=
        _dylib.lookupFunction<_c_heapsort, _dart_heapsort>('heapsort');
    return _heapsort(
      __base,
      __nel,
      __width,
      __compar,
    );
  }

  _dart_heapsort _heapsort;

  int mergesort(
    ffi.Pointer<ffi.Void> __base,
    int __nel,
    int __width,
    ffi.Pointer<ffi.NativeFunction<_typedefC_11>> __compar,
  ) {
    _mergesort ??=
        _dylib.lookupFunction<_c_mergesort, _dart_mergesort>('mergesort');
    return _mergesort(
      __base,
      __nel,
      __width,
      __compar,
    );
  }

  _dart_mergesort _mergesort;

  void psort(
    ffi.Pointer<ffi.Void> __base,
    int __nel,
    int __width,
    ffi.Pointer<ffi.NativeFunction<_typedefC_12>> __compar,
  ) {
    _psort ??= _dylib.lookupFunction<_c_psort, _dart_psort>('psort');
    return _psort(
      __base,
      __nel,
      __width,
      __compar,
    );
  }

  _dart_psort _psort;

  void psort_r(
    ffi.Pointer<ffi.Void> __base,
    int __nel,
    int __width,
    ffi.Pointer<ffi.Void> arg3,
    ffi.Pointer<ffi.NativeFunction<_typedefC_13>> __compar,
  ) {
    _psort_r ??= _dylib.lookupFunction<_c_psort_r, _dart_psort_r>('psort_r');
    return _psort_r(
      __base,
      __nel,
      __width,
      arg3,
      __compar,
    );
  }

  _dart_psort_r _psort_r;

  void qsort_r(
    ffi.Pointer<ffi.Void> __base,
    int __nel,
    int __width,
    ffi.Pointer<ffi.Void> arg3,
    ffi.Pointer<ffi.NativeFunction<_typedefC_14>> __compar,
  ) {
    _qsort_r ??= _dylib.lookupFunction<_c_qsort_r, _dart_qsort_r>('qsort_r');
    return _qsort_r(
      __base,
      __nel,
      __width,
      arg3,
      __compar,
    );
  }

  _dart_qsort_r _qsort_r;

  int radixsort(
    ffi.Pointer<ffi.Pointer<ffi.Uint8>> __base,
    int __nel,
    ffi.Pointer<ffi.Uint8> __table,
    int __endbyte,
  ) {
    _radixsort ??=
        _dylib.lookupFunction<_c_radixsort, _dart_radixsort>('radixsort');
    return _radixsort(
      __base,
      __nel,
      __table,
      __endbyte,
    );
  }

  _dart_radixsort _radixsort;

  int rpmatch(
    ffi.Pointer<ffi.Int8> arg0,
  ) {
    _rpmatch ??= _dylib.lookupFunction<_c_rpmatch, _dart_rpmatch>('rpmatch');
    return _rpmatch(
      arg0,
    );
  }

  _dart_rpmatch _rpmatch;

  int sradixsort(
    ffi.Pointer<ffi.Pointer<ffi.Uint8>> __base,
    int __nel,
    ffi.Pointer<ffi.Uint8> __table,
    int __endbyte,
  ) {
    _sradixsort ??=
        _dylib.lookupFunction<_c_sradixsort, _dart_sradixsort>('sradixsort');
    return _sradixsort(
      __base,
      __nel,
      __table,
      __endbyte,
    );
  }

  _dart_sradixsort _sradixsort;

  void sranddev() {
    _sranddev ??=
        _dylib.lookupFunction<_c_sranddev, _dart_sranddev>('sranddev');
    return _sranddev();
  }

  _dart_sranddev _sranddev;

  void srandomdev() {
    _srandomdev ??=
        _dylib.lookupFunction<_c_srandomdev, _dart_srandomdev>('srandomdev');
    return _srandomdev();
  }

  _dart_srandomdev _srandomdev;

  ffi.Pointer<ffi.Void> reallocf(
    ffi.Pointer<ffi.Void> __ptr,
    int __size,
  ) {
    _reallocf ??=
        _dylib.lookupFunction<_c_reallocf, _dart_reallocf>('reallocf');
    return _reallocf(
      __ptr,
      __size,
    );
  }

  _dart_reallocf _reallocf;

  int strtoq(
    ffi.Pointer<ffi.Int8> __str,
    ffi.Pointer<ffi.Pointer<ffi.Int8>> __endptr,
    int __base,
  ) {
    _strtoq ??= _dylib.lookupFunction<_c_strtoq, _dart_strtoq>('strtoq');
    return _strtoq(
      __str,
      __endptr,
      __base,
    );
  }

  _dart_strtoq _strtoq;

  int strtouq(
    ffi.Pointer<ffi.Int8> __str,
    ffi.Pointer<ffi.Pointer<ffi.Int8>> __endptr,
    int __base,
  ) {
    _strtouq ??= _dylib.lookupFunction<_c_strtouq, _dart_strtouq>('strtouq');
    return _strtouq(
      __str,
      __endptr,
      __base,
    );
  }

  _dart_strtouq _strtouq;
}

class __darwin_pthread_handler_rec extends ffi.Struct {
  ffi.Pointer<ffi.NativeFunction<_typedefC_1>> __routine;

  ffi.Pointer<ffi.Void> __arg;

  ffi.Pointer<__darwin_pthread_handler_rec> __next;
}

class _opaque_pthread_attr_t extends ffi.Struct {}

class _opaque_pthread_cond_t extends ffi.Struct {}

class _opaque_pthread_condattr_t extends ffi.Struct {}

class _opaque_pthread_mutex_t extends ffi.Struct {}

class _opaque_pthread_mutexattr_t extends ffi.Struct {}

class _opaque_pthread_once_t extends ffi.Struct {}

class _opaque_pthread_rwlock_t extends ffi.Struct {}

class _opaque_pthread_rwlockattr_t extends ffi.Struct {}

class _opaque_pthread_t extends ffi.Struct {}

abstract class idtype_t {
  static const int P_ALL = 0;
  static const int P_PID = 1;
  static const int P_PGID = 2;
}

class __darwin_i386_thread_state extends ffi.Struct {
  @ffi.Uint32()
  int __eax;

  @ffi.Uint32()
  int __ebx;

  @ffi.Uint32()
  int __ecx;

  @ffi.Uint32()
  int __edx;

  @ffi.Uint32()
  int __edi;

  @ffi.Uint32()
  int __esi;

  @ffi.Uint32()
  int __ebp;

  @ffi.Uint32()
  int __esp;

  @ffi.Uint32()
  int __ss;

  @ffi.Uint32()
  int __eflags;

  @ffi.Uint32()
  int __eip;

  @ffi.Uint32()
  int __cs;

  @ffi.Uint32()
  int __ds;

  @ffi.Uint32()
  int __es;

  @ffi.Uint32()
  int __fs;

  @ffi.Uint32()
  int __gs;
}

// class __darwin_fp_control extends ffi.Struct{
//   @ffi.Uint16()
//   int __invalid;

//   @ffi.Uint16()
//   int __denorm;

//   @ffi.Uint16()
//   int __zdiv;

//   @ffi.Uint16()
//   int __ovrfl;

//   @ffi.Uint16()
//   int __undfl;

//   @ffi.Uint16()
//   int __precis;

//   @ffi.Uint16()
//   int ;

//   @ffi.Uint16()
//   int __pc;

//   @ffi.Uint16()
//   int __rc;

//   @ffi.Uint16()
//   int _1;

//   @ffi.Uint16()
//   int _2;

// }

class __darwin_fp_status extends ffi.Struct {
  @ffi.Uint16()
  int __invalid;

  @ffi.Uint16()
  int __denorm;

  @ffi.Uint16()
  int __zdiv;

  @ffi.Uint16()
  int __ovrfl;

  @ffi.Uint16()
  int __undfl;

  @ffi.Uint16()
  int __precis;

  @ffi.Uint16()
  int __stkflt;

  @ffi.Uint16()
  int __errsumm;

  @ffi.Uint16()
  int __c0;

  @ffi.Uint16()
  int __c1;

  @ffi.Uint16()
  int __c2;

  @ffi.Uint16()
  int __tos;

  @ffi.Uint16()
  int __c3;

  @ffi.Uint16()
  int __busy;
}

class __darwin_mmst_reg extends ffi.Struct {}

class __darwin_xmm_reg extends ffi.Struct {}

class __darwin_ymm_reg extends ffi.Struct {}

class __darwin_zmm_reg extends ffi.Struct {}

class __darwin_opmask_reg extends ffi.Struct {}

class __darwin_i386_float_state extends ffi.Struct {}

class __darwin_i386_avx_state extends ffi.Struct {}

class __darwin_i386_avx512_state extends ffi.Struct {}

class __darwin_i386_exception_state extends ffi.Struct {
  @ffi.Uint16()
  int __trapno;

  @ffi.Uint16()
  int __cpu;

  @ffi.Uint32()
  int __err;

  @ffi.Uint32()
  int __faultvaddr;
}

class __darwin_x86_debug_state32 extends ffi.Struct {
  @ffi.Uint32()
  int __dr0;

  @ffi.Uint32()
  int __dr1;

  @ffi.Uint32()
  int __dr2;

  @ffi.Uint32()
  int __dr3;

  @ffi.Uint32()
  int __dr4;

  @ffi.Uint32()
  int __dr5;

  @ffi.Uint32()
  int __dr6;

  @ffi.Uint32()
  int __dr7;
}

class __x86_pagein_state extends ffi.Struct {
  @ffi.Int32()
  int __pagein_error;
}

class __darwin_x86_thread_state64 extends ffi.Struct {
  @ffi.Uint64()
  int __rax;

  @ffi.Uint64()
  int __rbx;

  @ffi.Uint64()
  int __rcx;

  @ffi.Uint64()
  int __rdx;

  @ffi.Uint64()
  int __rdi;

  @ffi.Uint64()
  int __rsi;

  @ffi.Uint64()
  int __rbp;

  @ffi.Uint64()
  int __rsp;

  @ffi.Uint64()
  int __r8;

  @ffi.Uint64()
  int __r9;

  @ffi.Uint64()
  int __r10;

  @ffi.Uint64()
  int __r11;

  @ffi.Uint64()
  int __r12;

  @ffi.Uint64()
  int __r13;

  @ffi.Uint64()
  int __r14;

  @ffi.Uint64()
  int __r15;

  @ffi.Uint64()
  int __rip;

  @ffi.Uint64()
  int __rflags;

  @ffi.Uint64()
  int __cs;

  @ffi.Uint64()
  int __fs;

  @ffi.Uint64()
  int __gs;
}

class __darwin_x86_thread_full_state64 extends ffi.Struct {}

class __darwin_x86_float_state64 extends ffi.Struct {}

class __darwin_x86_avx_state64 extends ffi.Struct {}

class __darwin_x86_avx512_state64 extends ffi.Struct {}

class __darwin_x86_exception_state64 extends ffi.Struct {
  @ffi.Uint16()
  int __trapno;

  @ffi.Uint16()
  int __cpu;

  @ffi.Uint32()
  int __err;

  @ffi.Uint64()
  int __faultvaddr;
}

class __darwin_x86_debug_state64 extends ffi.Struct {
  @ffi.Uint64()
  int __dr0;

  @ffi.Uint64()
  int __dr1;

  @ffi.Uint64()
  int __dr2;

  @ffi.Uint64()
  int __dr3;

  @ffi.Uint64()
  int __dr4;

  @ffi.Uint64()
  int __dr5;

  @ffi.Uint64()
  int __dr6;

  @ffi.Uint64()
  int __dr7;
}

class __darwin_x86_cpmu_state64 extends ffi.Struct {}

class __darwin_mcontext32 extends ffi.Struct {}

class __darwin_mcontext_avx32 extends ffi.Struct {}

class __darwin_mcontext_avx512_32 extends ffi.Struct {}

class __darwin_mcontext64 extends ffi.Struct {}

class __darwin_mcontext64_full extends ffi.Struct {}

class __darwin_mcontext_avx64 extends ffi.Struct {}

class __darwin_mcontext_avx64_full extends ffi.Struct {}

class __darwin_mcontext_avx512_64 extends ffi.Struct {}

class __darwin_mcontext_avx512_64_full extends ffi.Struct {}

class __darwin_sigaltstack extends ffi.Struct {
  ffi.Pointer<ffi.Void> ss_sp;

  @ffi.Uint64()
  int ss_size;

  @ffi.Int32()
  int ss_flags;
}

class __darwin_ucontext extends ffi.Struct {}

class sigevent extends ffi.Struct {}

class __siginfo extends ffi.Struct {}

class siginfo_t extends ffi.Struct {}

class __sigaction extends ffi.Struct {}

class sigaction extends ffi.Struct {}

class sigvec extends ffi.Struct {
  ffi.Pointer<ffi.NativeFunction<_typedefC_4>> sv_handler;

  @ffi.Int32()
  int sv_mask;

  @ffi.Int32()
  int sv_flags;
}

class sigstack extends ffi.Struct {
  ffi.Pointer<ffi.Int8> ss_sp;

  @ffi.Int32()
  int ss_onstack;
}

class timeval extends ffi.Struct {
  @ffi.Int64()
  int tv_sec;

  @ffi.Int32()
  int tv_usec;
}

class rusage extends ffi.Struct {}

class rusage_info_v0 extends ffi.Struct {}

class rusage_info_v1 extends ffi.Struct {}

class rusage_info_v2 extends ffi.Struct {}

class rusage_info_v3 extends ffi.Struct {}

class rusage_info_v4 extends ffi.Struct {}

class rlimit extends ffi.Struct {
  @ffi.Uint64()
  int rlim_cur;

  @ffi.Uint64()
  int rlim_max;
}

class proc_rlimit_control_wakeupmon extends ffi.Struct {
  @ffi.Uint32()
  int wm_flags;

  @ffi.Int32()
  int wm_rate;
}

class div_t extends ffi.Struct {
  @ffi.Int32()
  int quot;

  @ffi.Int32()
  int rem;
}

class ldiv_t extends ffi.Struct {
  @ffi.Int64()
  int quot;

  @ffi.Int64()
  int rem;
}

class lldiv_t extends ffi.Struct {
  @ffi.Int64()
  int quot;

  @ffi.Int64()
  int rem;
}

const int __API_TO_BE_DEPRECATED = 100000;

const int __MAC_10_0 = 1000;

const int __MAC_10_1 = 1010;

const int __MAC_10_2 = 1020;

const int __MAC_10_3 = 1030;

const int __MAC_10_4 = 1040;

const int __MAC_10_5 = 1050;

const int __MAC_10_6 = 1060;

const int __MAC_10_7 = 1070;

const int __MAC_10_8 = 1080;

const int __MAC_10_9 = 1090;

const int __MAC_10_10 = 101000;

const int __MAC_10_10_2 = 101002;

const int __MAC_10_10_3 = 101003;

const int __MAC_10_11 = 101100;

const int __MAC_10_11_2 = 101102;

const int __MAC_10_11_3 = 101103;

const int __MAC_10_11_4 = 101104;

const int __MAC_10_12 = 101200;

const int __MAC_10_12_1 = 101201;

const int __MAC_10_12_2 = 101202;

const int __MAC_10_12_4 = 101204;

const int __MAC_10_13 = 101300;

const int __MAC_10_13_1 = 101301;

const int __MAC_10_13_2 = 101302;

const int __MAC_10_13_4 = 101304;

const int __MAC_10_14 = 101400;

const int __MAC_10_14_1 = 101401;

const int __MAC_10_14_4 = 101404;

const int __MAC_10_15 = 101500;

const int __MAC_10_15_1 = 101501;

const int __MAC_10_15_4 = 101504;

const int __IPHONE_2_0 = 20000;

const int __IPHONE_2_1 = 20100;

const int __IPHONE_2_2 = 20200;

const int __IPHONE_3_0 = 30000;

const int __IPHONE_3_1 = 30100;

const int __IPHONE_3_2 = 30200;

const int __IPHONE_4_0 = 40000;

const int __IPHONE_4_1 = 40100;

const int __IPHONE_4_2 = 40200;

const int __IPHONE_4_3 = 40300;

const int __IPHONE_5_0 = 50000;

const int __IPHONE_5_1 = 50100;

const int __IPHONE_6_0 = 60000;

const int __IPHONE_6_1 = 60100;

const int __IPHONE_7_0 = 70000;

const int __IPHONE_7_1 = 70100;

const int __IPHONE_8_0 = 80000;

const int __IPHONE_8_1 = 80100;

const int __IPHONE_8_2 = 80200;

const int __IPHONE_8_3 = 80300;

const int __IPHONE_8_4 = 80400;

const int __IPHONE_9_0 = 90000;

const int __IPHONE_9_1 = 90100;

const int __IPHONE_9_2 = 90200;

const int __IPHONE_9_3 = 90300;

const int __IPHONE_10_0 = 100000;

const int __IPHONE_10_1 = 100100;

const int __IPHONE_10_2 = 100200;

const int __IPHONE_10_3 = 100300;

const int __IPHONE_11_0 = 110000;

const int __IPHONE_11_1 = 110100;

const int __IPHONE_11_2 = 110200;

const int __IPHONE_11_3 = 110300;

const int __IPHONE_11_4 = 110400;

const int __IPHONE_12_0 = 120000;

const int __IPHONE_12_1 = 120100;

const int __IPHONE_12_2 = 120200;

const int __IPHONE_12_3 = 120300;

const int __IPHONE_13_0 = 130000;

const int __IPHONE_13_1 = 130100;

const int __IPHONE_13_2 = 130200;

const int __IPHONE_13_3 = 130300;

const int __IPHONE_13_4 = 130400;

const int __TVOS_9_0 = 90000;

const int __TVOS_9_1 = 90100;

const int __TVOS_9_2 = 90200;

const int __TVOS_10_0 = 100000;

const int __TVOS_10_0_1 = 100001;

const int __TVOS_10_1 = 100100;

const int __TVOS_10_2 = 100200;

const int __TVOS_11_0 = 110000;

const int __TVOS_11_1 = 110100;

const int __TVOS_11_2 = 110200;

const int __TVOS_11_3 = 110300;

const int __TVOS_11_4 = 110400;

const int __TVOS_12_0 = 120000;

const int __TVOS_12_1 = 120100;

const int __TVOS_12_2 = 120200;

const int __TVOS_12_3 = 120300;

const int __TVOS_13_0 = 130000;

const int __TVOS_13_2 = 130200;

const int __TVOS_13_3 = 130300;

const int __TVOS_13_4 = 130400;

const int __WATCHOS_1_0 = 10000;

const int __WATCHOS_2_0 = 20000;

const int __WATCHOS_2_1 = 20100;

const int __WATCHOS_2_2 = 20200;

const int __WATCHOS_3_0 = 30000;

const int __WATCHOS_3_1 = 30100;

const int __WATCHOS_3_1_1 = 30101;

const int __WATCHOS_3_2 = 30200;

const int __WATCHOS_4_0 = 40000;

const int __WATCHOS_4_1 = 40100;

const int __WATCHOS_4_2 = 40200;

const int __WATCHOS_4_3 = 40300;

const int __WATCHOS_5_0 = 50000;

const int __WATCHOS_5_1 = 50100;

const int __WATCHOS_5_2 = 50200;

const int __WATCHOS_6_0 = 60000;

const int __WATCHOS_6_1 = 60100;

const int __WATCHOS_6_2 = 60200;

const int __DRIVERKIT_19_0 = 190000;

const int __MAC_OS_X_VERSION_MIN_REQUIRED = 101500;

const int __MAC_OS_X_VERSION_MAX_ALLOWED = 101500;

const int __ENABLE_LEGACY_MAC_AVAILABILITY = 1;

const int __DARWIN_ONLY_64_BIT_INO_T = 0;

const int __DARWIN_ONLY_VERS_1050 = 0;

const int __DARWIN_ONLY_UNIX_CONFORMANCE = 1;

const int __DARWIN_UNIX03 = 1;

const int __DARWIN_64_BIT_INO_T = 1;

const int __DARWIN_VERS_1050 = 1;

const int __DARWIN_NON_CANCELABLE = 0;

// const String __DARWIN_SUF_64_BIT_INO_T = '$INODE64';

// const String __DARWIN_SUF_1050 = '$1050';

// const String __DARWIN_SUF_EXTSN = '$DARWIN_EXTSN';

const int __DARWIN_C_ANSI = 4096;

const int __DARWIN_C_FULL = 900000;

const int __DARWIN_C_LEVEL = 900000;

const int __STDC_WANT_LIB_EXT1__ = 1;

const int __DARWIN_NO_LONG_LONG = 0;

const int _DARWIN_FEATURE_64_BIT_INODE = 1;

const int _DARWIN_FEATURE_ONLY_UNIX_CONFORMANCE = 1;

const int _DARWIN_FEATURE_UNIX_CONFORMANCE = 3;

const int __DARWIN_NULL = 0;

const int __PTHREAD_SIZE__ = 8176;

const int __PTHREAD_ATTR_SIZE__ = 56;

const int __PTHREAD_MUTEXATTR_SIZE__ = 8;

const int __PTHREAD_MUTEX_SIZE__ = 56;

const int __PTHREAD_CONDATTR_SIZE__ = 8;

const int __PTHREAD_COND_SIZE__ = 40;

const int __PTHREAD_ONCE_SIZE__ = 8;

const int __PTHREAD_RWLOCK_SIZE__ = 192;

const int __PTHREAD_RWLOCKATTR_SIZE__ = 16;

const int __DARWIN_WCHAR_MAX = 2147483647;

const int __DARWIN_WCHAR_MIN = -2147483648;

const int __DARWIN_WEOF = -1;

const int _FORTIFY_SOURCE = 2;

const int __DARWIN_NSIG = 32;

const int NSIG = 32;

const int _I386_SIGNAL_H_ = 1;

const int SIGHUP = 1;

const int SIGINT = 2;

const int SIGQUIT = 3;

const int SIGILL = 4;

const int SIGTRAP = 5;

const int SIGABRT = 6;

const int SIGIOT = 6;

const int SIGEMT = 7;

const int SIGFPE = 8;

const int SIGKILL = 9;

const int SIGBUS = 10;

const int SIGSEGV = 11;

const int SIGSYS = 12;

const int SIGPIPE = 13;

const int SIGALRM = 14;

const int SIGTERM = 15;

const int SIGURG = 16;

const int SIGSTOP = 17;

const int SIGTSTP = 18;

const int SIGCONT = 19;

const int SIGCHLD = 20;

const int SIGTTIN = 21;

const int SIGTTOU = 22;

const int SIGIO = 23;

const int SIGXCPU = 24;

const int SIGXFSZ = 25;

const int SIGVTALRM = 26;

const int SIGPROF = 27;

const int SIGWINCH = 28;

const int SIGINFO = 29;

const int SIGUSR1 = 30;

const int SIGUSR2 = 31;

const int USER_ADDR_NULL = 0;

const int FP_PREC_24B = 0;

const int FP_PREC_53B = 2;

const int FP_PREC_64B = 3;

const int FP_RND_NEAR = 0;

const int FP_RND_DOWN = 1;

const int FP_RND_UP = 2;

const int FP_CHOP = 3;

const int FP_STATE_BYTES = 512;

const int SIGEV_NONE = 0;

const int SIGEV_SIGNAL = 1;

const int SIGEV_THREAD = 3;

const int ILL_NOOP = 0;

const int ILL_ILLOPC = 1;

const int ILL_ILLTRP = 2;

const int ILL_PRVOPC = 3;

const int ILL_ILLOPN = 4;

const int ILL_ILLADR = 5;

const int ILL_PRVREG = 6;

const int ILL_COPROC = 7;

const int ILL_BADSTK = 8;

const int FPE_NOOP = 0;

const int FPE_FLTDIV = 1;

const int FPE_FLTOVF = 2;

const int FPE_FLTUND = 3;

const int FPE_FLTRES = 4;

const int FPE_FLTINV = 5;

const int FPE_FLTSUB = 6;

const int FPE_INTDIV = 7;

const int FPE_INTOVF = 8;

const int SEGV_NOOP = 0;

const int SEGV_MAPERR = 1;

const int SEGV_ACCERR = 2;

const int BUS_NOOP = 0;

const int BUS_ADRALN = 1;

const int BUS_ADRERR = 2;

const int BUS_OBJERR = 3;

const int TRAP_BRKPT = 1;

const int TRAP_TRACE = 2;

const int CLD_NOOP = 0;

const int CLD_EXITED = 1;

const int CLD_KILLED = 2;

const int CLD_DUMPED = 3;

const int CLD_TRAPPED = 4;

const int CLD_STOPPED = 5;

const int CLD_CONTINUED = 6;

const int POLL_IN = 1;

const int POLL_OUT = 2;

const int POLL_MSG = 3;

const int POLL_ERR = 4;

const int POLL_PRI = 5;

const int POLL_HUP = 6;

const int SA_ONSTACK = 1;

const int SA_RESTART = 2;

const int SA_RESETHAND = 4;

const int SA_NOCLDSTOP = 8;

const int SA_NODEFER = 16;

const int SA_NOCLDWAIT = 32;

const int SA_SIGINFO = 64;

const int SA_USERTRAMP = 256;

const int SA_64REGSET = 512;

const int SA_USERSPACE_MASK = 127;

const int SIG_BLOCK = 1;

const int SIG_UNBLOCK = 2;

const int SIG_SETMASK = 3;

const int SI_USER = 65537;

const int SI_QUEUE = 65538;

const int SI_TIMER = 65539;

const int SI_ASYNCIO = 65540;

const int SI_MESGQ = 65541;

const int SS_ONSTACK = 1;

const int SS_DISABLE = 4;

const int MINSIGSTKSZ = 32768;

const int SIGSTKSZ = 131072;

const int SV_ONSTACK = 1;

const int SV_INTERRUPT = 2;

const int SV_RESETHAND = 4;

const int SV_NODEFER = 16;

const int SV_NOCLDSTOP = 8;

const int SV_SIGINFO = 64;

const int __WORDSIZE = 64;

const int INT8_MAX = 127;

const int INT16_MAX = 32767;

const int INT32_MAX = 2147483647;

const int INT64_MAX = 9223372036854775807;

const int INT8_MIN = -128;

const int INT16_MIN = -32768;

const int INT32_MIN = -2147483648;

const int INT64_MIN = -9223372036854775808;

const int UINT8_MAX = 255;

const int UINT16_MAX = 65535;

const int UINT32_MAX = 4294967295;

const int UINT64_MAX = -1;

const int INT_LEAST8_MIN = -128;

const int INT_LEAST16_MIN = -32768;

const int INT_LEAST32_MIN = -2147483648;

const int INT_LEAST64_MIN = -9223372036854775808;

const int INT_LEAST8_MAX = 127;

const int INT_LEAST16_MAX = 32767;

const int INT_LEAST32_MAX = 2147483647;

const int INT_LEAST64_MAX = 9223372036854775807;

const int UINT_LEAST8_MAX = 255;

const int UINT_LEAST16_MAX = 65535;

const int UINT_LEAST32_MAX = 4294967295;

const int UINT_LEAST64_MAX = -1;

const int INT_FAST8_MIN = -128;

const int INT_FAST16_MIN = -32768;

const int INT_FAST32_MIN = -2147483648;

const int INT_FAST64_MIN = -9223372036854775808;

const int INT_FAST8_MAX = 127;

const int INT_FAST16_MAX = 32767;

const int INT_FAST32_MAX = 2147483647;

const int INT_FAST64_MAX = 9223372036854775807;

const int UINT_FAST8_MAX = 255;

const int UINT_FAST16_MAX = 65535;

const int UINT_FAST32_MAX = 4294967295;

const int UINT_FAST64_MAX = -1;

const int INTPTR_MAX = 9223372036854775807;

const int INTPTR_MIN = -9223372036854775808;

const int UINTPTR_MAX = -1;

const int INTMAX_MAX = 9223372036854775807;

const int UINTMAX_MAX = -1;

const int INTMAX_MIN = -9223372036854775808;

const int PTRDIFF_MIN = -9223372036854775808;

const int PTRDIFF_MAX = 9223372036854775807;

const int SIZE_MAX = -1;

const int RSIZE_MAX = 9223372036854775807;

const int WCHAR_MAX = 2147483647;

const int WCHAR_MIN = -2147483648;

const int WINT_MIN = -2147483648;

const int WINT_MAX = 2147483647;

const int SIG_ATOMIC_MIN = -2147483648;

const int SIG_ATOMIC_MAX = 2147483647;

const int PRIO_PROCESS = 0;

const int PRIO_PGRP = 1;

const int PRIO_USER = 2;

const int PRIO_DARWIN_THREAD = 3;

const int PRIO_DARWIN_PROCESS = 4;

const int PRIO_MIN = -20;

const int PRIO_MAX = 20;

const int PRIO_DARWIN_BG = 4096;

const int PRIO_DARWIN_NONUI = 4097;

const int RUSAGE_SELF = 0;

const int RUSAGE_CHILDREN = -1;

const int RUSAGE_INFO_V0 = 0;

const int RUSAGE_INFO_V1 = 1;

const int RUSAGE_INFO_V2 = 2;

const int RUSAGE_INFO_V3 = 3;

const int RUSAGE_INFO_V4 = 4;

const int RUSAGE_INFO_CURRENT = 4;

const int RLIM_INFINITY = 9223372036854775807;

const int RLIM_SAVED_MAX = 9223372036854775807;

const int RLIM_SAVED_CUR = 9223372036854775807;

const int RLIMIT_CPU = 0;

const int RLIMIT_FSIZE = 1;

const int RLIMIT_DATA = 2;

const int RLIMIT_STACK = 3;

const int RLIMIT_CORE = 4;

const int RLIMIT_AS = 5;

const int RLIMIT_RSS = 5;

const int RLIMIT_MEMLOCK = 6;

const int RLIMIT_NPROC = 7;

const int RLIMIT_NOFILE = 8;

const int RLIM_NLIMITS = 9;

const int _RLIMIT_POSIX_FLAG = 4096;

const int RLIMIT_WAKEUPS_MONITOR = 1;

const int RLIMIT_CPU_USAGE_MONITOR = 2;

const int RLIMIT_THREAD_CPULIMITS = 3;

const int RLIMIT_FOOTPRINT_INTERVAL = 4;

const int WAKEMON_ENABLE = 1;

const int WAKEMON_DISABLE = 2;

const int WAKEMON_GET_PARAMS = 4;

const int WAKEMON_SET_DEFAULTS = 8;

const int WAKEMON_MAKE_FATAL = 16;

const int CPUMON_MAKE_FATAL = 4096;

const int FOOTPRINT_INTERVAL_RESET = 1;

const int IOPOL_TYPE_DISK = 0;

const int IOPOL_TYPE_VFS_ATIME_UPDATES = 2;

const int IOPOL_TYPE_VFS_MATERIALIZE_DATALESS_FILES = 3;

const int IOPOL_TYPE_VFS_STATFS_NO_DATA_VOLUME = 4;

const int IOPOL_SCOPE_PROCESS = 0;

const int IOPOL_SCOPE_THREAD = 1;

const int IOPOL_SCOPE_DARWIN_BG = 2;

const int IOPOL_DEFAULT = 0;

const int IOPOL_IMPORTANT = 1;

const int IOPOL_PASSIVE = 2;

const int IOPOL_THROTTLE = 3;

const int IOPOL_UTILITY = 4;

const int IOPOL_STANDARD = 5;

const int IOPOL_APPLICATION = 5;

const int IOPOL_NORMAL = 1;

const int IOPOL_ATIME_UPDATES_DEFAULT = 0;

const int IOPOL_ATIME_UPDATES_OFF = 1;

const int IOPOL_MATERIALIZE_DATALESS_FILES_DEFAULT = 0;

const int IOPOL_MATERIALIZE_DATALESS_FILES_OFF = 1;

const int IOPOL_MATERIALIZE_DATALESS_FILES_ON = 2;

const int IOPOL_VFS_STATFS_NO_DATA_VOLUME_DEFAULT = 0;

const int IOPOL_VFS_STATFS_FORCE_NO_DATA_VOLUME = 1;

const int WNOHANG = 1;

const int WUNTRACED = 2;

const int WCOREFLAG = 128;

const int _WSTOPPED = 127;

const int WEXITED = 4;

const int WSTOPPED = 8;

const int WCONTINUED = 16;

const int WNOWAIT = 32;

const int WAIT_ANY = -1;

const int WAIT_MYPGRP = 0;

const int _QUAD_HIGHWORD = 1;

const int _QUAD_LOWWORD = 0;

const int __DARWIN_LITTLE_ENDIAN = 1234;

const int __DARWIN_BIG_ENDIAN = 4321;

const int __DARWIN_PDP_ENDIAN = 3412;

const int __DARWIN_BYTE_ORDER = 1234;

const int LITTLE_ENDIAN = 1234;

const int BIG_ENDIAN = 4321;

const int PDP_ENDIAN = 3412;

const int BYTE_ORDER = 1234;

const int NULL = 0;

const int EXIT_FAILURE = 1;

const int EXIT_SUCCESS = 0;

const int RAND_MAX = 2147483647;

typedef _typedefC_6 = ffi.Void Function(
  ffi.Int32,
);

// typedef _c_signal = ffi.Pointer<ffi.NativeFunction<_typedefC_5>> Function(
//   ffi.Int32 arg0,
//   ffi.Pointer<ffi.NativeFunction<_typedefC_6>> arg1,
// );

// typedef _dart_signal = ffi.Pointer<ffi.NativeFunction<_typedefC_5>> Function(
//   int arg0,
//   ffi.Pointer<ffi.NativeFunction<_typedefC_6>> arg1,
// );

typedef _c_getpriority = ffi.Int32 Function(
  ffi.Int32 arg0,
  ffi.Uint32 arg1,
);

typedef _dart_getpriority = int Function(
  int arg0,
  int arg1,
);

typedef _c_getiopolicy_np = ffi.Int32 Function(
  ffi.Int32 arg0,
  ffi.Int32 arg1,
);

typedef _dart_getiopolicy_np = int Function(
  int arg0,
  int arg1,
);

typedef _c_getrlimit = ffi.Int32 Function(
  ffi.Int32 arg0,
  ffi.Pointer<rlimit> arg1,
);

typedef _dart_getrlimit = int Function(
  int arg0,
  ffi.Pointer<rlimit> arg1,
);

typedef _c_getrusage = ffi.Int32 Function(
  ffi.Int32 arg0,
  ffi.Pointer<rusage> arg1,
);

typedef _dart_getrusage = int Function(
  int arg0,
  ffi.Pointer<rusage> arg1,
);

typedef _c_setpriority = ffi.Int32 Function(
  ffi.Int32 arg0,
  ffi.Uint32 arg1,
  ffi.Int32 arg2,
);

typedef _dart_setpriority = int Function(
  int arg0,
  int arg1,
  int arg2,
);

typedef _c_setiopolicy_np = ffi.Int32 Function(
  ffi.Int32 arg0,
  ffi.Int32 arg1,
  ffi.Int32 arg2,
);

typedef _dart_setiopolicy_np = int Function(
  int arg0,
  int arg1,
  int arg2,
);

typedef _c_setrlimit = ffi.Int32 Function(
  ffi.Int32 arg0,
  ffi.Pointer<rlimit> arg1,
);

typedef _dart_setrlimit = int Function(
  int arg0,
  ffi.Pointer<rlimit> arg1,
);

typedef _c__OSSwapInt16 = ffi.Uint16 Function(
  ffi.Uint16 _data,
);

typedef _dart__OSSwapInt16 = int Function(
  int _data,
);

typedef _c__OSSwapInt32 = ffi.Uint32 Function(
  ffi.Uint32 _data,
);

typedef _dart__OSSwapInt32 = int Function(
  int _data,
);

typedef _c__OSSwapInt64 = ffi.Uint64 Function(
  ffi.Uint64 _data,
);

typedef _dart__OSSwapInt64 = int Function(
  int _data,
);

typedef _c_wait = ffi.Int32 Function(
  ffi.Pointer<ffi.Int32> arg0,
);

typedef _dart_wait = int Function(
  ffi.Pointer<ffi.Int32> arg0,
);

typedef _c_waitpid = ffi.Int32 Function(
  ffi.Int32 arg0,
  ffi.Pointer<ffi.Int32> arg1,
  ffi.Int32 arg2,
);

typedef _dart_waitpid = int Function(
  int arg0,
  ffi.Pointer<ffi.Int32> arg1,
  int arg2,
);

typedef _c_waitid = ffi.Int32 Function(
  ffi.Int32 arg0,
  ffi.Uint32 arg1,
  ffi.Pointer<__siginfo> arg2,
  ffi.Int32 arg3,
);

typedef _dart_waitid = int Function(
  int arg0,
  int arg1,
  ffi.Pointer<__siginfo> arg2,
  int arg3,
);

typedef _c_wait3 = ffi.Int32 Function(
  ffi.Pointer<ffi.Int32> arg0,
  ffi.Int32 arg1,
  ffi.Pointer<rusage> arg2,
);

typedef _dart_wait3 = int Function(
  ffi.Pointer<ffi.Int32> arg0,
  int arg1,
  ffi.Pointer<rusage> arg2,
);

typedef _c_wait4 = ffi.Int32 Function(
  ffi.Int32 arg0,
  ffi.Pointer<ffi.Int32> arg1,
  ffi.Int32 arg2,
  ffi.Pointer<rusage> arg3,
);

typedef _dart_wait4 = int Function(
  int arg0,
  ffi.Pointer<ffi.Int32> arg1,
  int arg2,
  ffi.Pointer<rusage> arg3,
);

typedef _c_alloca = ffi.Pointer<ffi.Void> Function(
  ffi.Uint64 arg0,
);

typedef _dart_alloca = ffi.Pointer<ffi.Void> Function(
  int arg0,
);

typedef _c_malloc = ffi.Pointer<ffi.Void> Function(
  ffi.Uint64 __size,
);

typedef _dart_malloc = ffi.Pointer<ffi.Void> Function(
  int __size,
);

typedef _c_calloc = ffi.Pointer<ffi.Void> Function(
  ffi.Uint64 __count,
  ffi.Uint64 __size,
);

typedef _dart_calloc = ffi.Pointer<ffi.Void> Function(
  int __count,
  int __size,
);

typedef _c_free = ffi.Void Function(
  ffi.Pointer<ffi.Void> arg0,
);

typedef _dart_free = void Function(
  ffi.Pointer<ffi.Void> arg0,
);

typedef _c_realloc = ffi.Pointer<ffi.Void> Function(
  ffi.Pointer<ffi.Void> __ptr,
  ffi.Uint64 __size,
);

typedef _dart_realloc = ffi.Pointer<ffi.Void> Function(
  ffi.Pointer<ffi.Void> __ptr,
  int __size,
);

typedef _c_valloc = ffi.Pointer<ffi.Void> Function(
  ffi.Uint64 arg0,
);

typedef _dart_valloc = ffi.Pointer<ffi.Void> Function(
  int arg0,
);

typedef _c_aligned_alloc = ffi.Pointer<ffi.Void> Function(
  ffi.Uint64 __alignment,
  ffi.Uint64 __size,
);

typedef _dart_aligned_alloc = ffi.Pointer<ffi.Void> Function(
  int __alignment,
  int __size,
);

typedef _c_posix_memalign = ffi.Int32 Function(
  ffi.Pointer<ffi.Pointer<ffi.Void>> __memptr,
  ffi.Uint64 __alignment,
  ffi.Uint64 __size,
);

typedef _dart_posix_memalign = int Function(
  ffi.Pointer<ffi.Pointer<ffi.Void>> __memptr,
  int __alignment,
  int __size,
);

typedef _c_abort = ffi.Void Function();

typedef _dart_abort = void Function();

typedef _c_abs = ffi.Int32 Function(
  ffi.Int32 arg0,
);

typedef _dart_abs = int Function(
  int arg0,
);

typedef _typedefC_7 = ffi.Void Function();

typedef _c_atexit = ffi.Int32 Function(
  ffi.Pointer<ffi.NativeFunction<_typedefC_7>> arg0,
);

typedef _dart_atexit = int Function(
  ffi.Pointer<ffi.NativeFunction<_typedefC_7>> arg0,
);

typedef _c_atof = ffi.Double Function(
  ffi.Pointer<ffi.Int8> arg0,
);

typedef _dart_atof = double Function(
  ffi.Pointer<ffi.Int8> arg0,
);

typedef _c_atoi = ffi.Int32 Function(
  ffi.Pointer<ffi.Int8> arg0,
);

typedef _dart_atoi = int Function(
  ffi.Pointer<ffi.Int8> arg0,
);

typedef _c_atol = ffi.Int64 Function(
  ffi.Pointer<ffi.Int8> arg0,
);

typedef _dart_atol = int Function(
  ffi.Pointer<ffi.Int8> arg0,
);

typedef _c_atoll = ffi.Int64 Function(
  ffi.Pointer<ffi.Int8> arg0,
);

typedef _dart_atoll = int Function(
  ffi.Pointer<ffi.Int8> arg0,
);

typedef _typedefC_8 = ffi.Int32 Function(
  ffi.Pointer<ffi.Void>,
  ffi.Pointer<ffi.Void>,
);

typedef _c_bsearch = ffi.Pointer<ffi.Void> Function(
  ffi.Pointer<ffi.Void> __key,
  ffi.Pointer<ffi.Void> __base,
  ffi.Uint64 __nel,
  ffi.Uint64 __width,
  ffi.Pointer<ffi.NativeFunction<_typedefC_8>> __compar,
);

typedef _dart_bsearch = ffi.Pointer<ffi.Void> Function(
  ffi.Pointer<ffi.Void> __key,
  ffi.Pointer<ffi.Void> __base,
  int __nel,
  int __width,
  ffi.Pointer<ffi.NativeFunction<_typedefC_8>> __compar,
);

typedef _c_exit = ffi.Void Function(
  ffi.Int32 arg0,
);

typedef _dart_exit = void Function(
  int arg0,
);

typedef _c_getenv = ffi.Pointer<ffi.Int8> Function(
  ffi.Pointer<ffi.Int8> arg0,
);

typedef _dart_getenv = ffi.Pointer<ffi.Int8> Function(
  ffi.Pointer<ffi.Int8> arg0,
);

typedef _c_labs = ffi.Int64 Function(
  ffi.Int64 arg0,
);

typedef _dart_labs = int Function(
  int arg0,
);

typedef _c_llabs = ffi.Int64 Function(
  ffi.Int64 arg0,
);

typedef _dart_llabs = int Function(
  int arg0,
);

typedef _c_mblen = ffi.Int32 Function(
  ffi.Pointer<ffi.Int8> __s,
  ffi.Uint64 __n,
);

typedef _dart_mblen = int Function(
  ffi.Pointer<ffi.Int8> __s,
  int __n,
);

typedef _c_mbstowcs = ffi.Uint64 Function(
  ffi.Pointer<ffi.Int32> arg0,
  ffi.Pointer<ffi.Int8> arg1,
  ffi.Uint64 arg2,
);

typedef _dart_mbstowcs = int Function(
  ffi.Pointer<ffi.Int32> arg0,
  ffi.Pointer<ffi.Int8> arg1,
  int arg2,
);

typedef _c_mbtowc = ffi.Int32 Function(
  ffi.Pointer<ffi.Int32> arg0,
  ffi.Pointer<ffi.Int8> arg1,
  ffi.Uint64 arg2,
);

typedef _dart_mbtowc = int Function(
  ffi.Pointer<ffi.Int32> arg0,
  ffi.Pointer<ffi.Int8> arg1,
  int arg2,
);

typedef _typedefC_9 = ffi.Int32 Function(
  ffi.Pointer<ffi.Void>,
  ffi.Pointer<ffi.Void>,
);

typedef _c_qsort = ffi.Void Function(
  ffi.Pointer<ffi.Void> __base,
  ffi.Uint64 __nel,
  ffi.Uint64 __width,
  ffi.Pointer<ffi.NativeFunction<_typedefC_9>> __compar,
);

typedef _dart_qsort = void Function(
  ffi.Pointer<ffi.Void> __base,
  int __nel,
  int __width,
  ffi.Pointer<ffi.NativeFunction<_typedefC_9>> __compar,
);

typedef _c_rand = ffi.Int32 Function();

typedef _dart_rand = int Function();

typedef _c_srand = ffi.Void Function(
  ffi.Uint32 arg0,
);

typedef _dart_srand = void Function(
  int arg0,
);

typedef _c_strtod = ffi.Double Function(
  ffi.Pointer<ffi.Int8> arg0,
  ffi.Pointer<ffi.Pointer<ffi.Int8>> arg1,
);

typedef _dart_strtod = double Function(
  ffi.Pointer<ffi.Int8> arg0,
  ffi.Pointer<ffi.Pointer<ffi.Int8>> arg1,
);

typedef _c_strtof = ffi.Float Function(
  ffi.Pointer<ffi.Int8> arg0,
  ffi.Pointer<ffi.Pointer<ffi.Int8>> arg1,
);

typedef _dart_strtof = double Function(
  ffi.Pointer<ffi.Int8> arg0,
  ffi.Pointer<ffi.Pointer<ffi.Int8>> arg1,
);

typedef _c_strtol = ffi.Int64 Function(
  ffi.Pointer<ffi.Int8> __str,
  ffi.Pointer<ffi.Pointer<ffi.Int8>> __endptr,
  ffi.Int32 __base,
);

typedef _dart_strtol = int Function(
  ffi.Pointer<ffi.Int8> __str,
  ffi.Pointer<ffi.Pointer<ffi.Int8>> __endptr,
  int __base,
);

typedef _c_strtoll = ffi.Int64 Function(
  ffi.Pointer<ffi.Int8> __str,
  ffi.Pointer<ffi.Pointer<ffi.Int8>> __endptr,
  ffi.Int32 __base,
);

typedef _dart_strtoll = int Function(
  ffi.Pointer<ffi.Int8> __str,
  ffi.Pointer<ffi.Pointer<ffi.Int8>> __endptr,
  int __base,
);

typedef _c_strtoul = ffi.Uint64 Function(
  ffi.Pointer<ffi.Int8> __str,
  ffi.Pointer<ffi.Pointer<ffi.Int8>> __endptr,
  ffi.Int32 __base,
);

typedef _dart_strtoul = int Function(
  ffi.Pointer<ffi.Int8> __str,
  ffi.Pointer<ffi.Pointer<ffi.Int8>> __endptr,
  int __base,
);

typedef _c_strtoull = ffi.Uint64 Function(
  ffi.Pointer<ffi.Int8> __str,
  ffi.Pointer<ffi.Pointer<ffi.Int8>> __endptr,
  ffi.Int32 __base,
);

typedef _dart_strtoull = int Function(
  ffi.Pointer<ffi.Int8> __str,
  ffi.Pointer<ffi.Pointer<ffi.Int8>> __endptr,
  int __base,
);

typedef _c_system = ffi.Int32 Function(
  ffi.Pointer<ffi.Int8> arg0,
);

typedef _dart_system = int Function(
  ffi.Pointer<ffi.Int8> arg0,
);

typedef _c_wcstombs = ffi.Uint64 Function(
  ffi.Pointer<ffi.Int8> arg0,
  ffi.Pointer<ffi.Int32> arg1,
  ffi.Uint64 arg2,
);

typedef _dart_wcstombs = int Function(
  ffi.Pointer<ffi.Int8> arg0,
  ffi.Pointer<ffi.Int32> arg1,
  int arg2,
);

typedef _c_wctomb = ffi.Int32 Function(
  ffi.Pointer<ffi.Int8> arg0,
  ffi.Int32 arg1,
);

typedef _dart_wctomb = int Function(
  ffi.Pointer<ffi.Int8> arg0,
  int arg1,
);

typedef _c__Exit = ffi.Void Function(
  ffi.Int32 arg0,
);

typedef _dart__Exit = void Function(
  int arg0,
);

typedef _c_a64l = ffi.Int64 Function(
  ffi.Pointer<ffi.Int8> arg0,
);

typedef _dart_a64l = int Function(
  ffi.Pointer<ffi.Int8> arg0,
);

typedef _c_drand48 = ffi.Double Function();

typedef _dart_drand48 = double Function();

typedef _c_ecvt = ffi.Pointer<ffi.Int8> Function(
  ffi.Double arg0,
  ffi.Int32 arg1,
  ffi.Pointer<ffi.Int32> arg2,
  ffi.Pointer<ffi.Int32> arg3,
);

typedef _dart_ecvt = ffi.Pointer<ffi.Int8> Function(
  double arg0,
  int arg1,
  ffi.Pointer<ffi.Int32> arg2,
  ffi.Pointer<ffi.Int32> arg3,
);

typedef _c_erand48 = ffi.Double Function(
  ffi.Pointer<ffi.Uint16> arg0,
);

typedef _dart_erand48 = double Function(
  ffi.Pointer<ffi.Uint16> arg0,
);

typedef _c_fcvt = ffi.Pointer<ffi.Int8> Function(
  ffi.Double arg0,
  ffi.Int32 arg1,
  ffi.Pointer<ffi.Int32> arg2,
  ffi.Pointer<ffi.Int32> arg3,
);

typedef _dart_fcvt = ffi.Pointer<ffi.Int8> Function(
  double arg0,
  int arg1,
  ffi.Pointer<ffi.Int32> arg2,
  ffi.Pointer<ffi.Int32> arg3,
);

typedef _c_gcvt = ffi.Pointer<ffi.Int8> Function(
  ffi.Double arg0,
  ffi.Int32 arg1,
  ffi.Pointer<ffi.Int8> arg2,
);

typedef _dart_gcvt = ffi.Pointer<ffi.Int8> Function(
  double arg0,
  int arg1,
  ffi.Pointer<ffi.Int8> arg2,
);

typedef _c_getsubopt = ffi.Int32 Function(
  ffi.Pointer<ffi.Pointer<ffi.Int8>> arg0,
  ffi.Pointer<ffi.Pointer<ffi.Int8>> arg1,
  ffi.Pointer<ffi.Pointer<ffi.Int8>> arg2,
);

typedef _dart_getsubopt = int Function(
  ffi.Pointer<ffi.Pointer<ffi.Int8>> arg0,
  ffi.Pointer<ffi.Pointer<ffi.Int8>> arg1,
  ffi.Pointer<ffi.Pointer<ffi.Int8>> arg2,
);

typedef _c_grantpt = ffi.Int32 Function(
  ffi.Int32 arg0,
);

typedef _dart_grantpt = int Function(
  int arg0,
);

typedef _c_initstate = ffi.Pointer<ffi.Int8> Function(
  ffi.Uint32 arg0,
  ffi.Pointer<ffi.Int8> arg1,
  ffi.Uint64 arg2,
);

typedef _dart_initstate = ffi.Pointer<ffi.Int8> Function(
  int arg0,
  ffi.Pointer<ffi.Int8> arg1,
  int arg2,
);

typedef _c_jrand48 = ffi.Int64 Function(
  ffi.Pointer<ffi.Uint16> arg0,
);

typedef _dart_jrand48 = int Function(
  ffi.Pointer<ffi.Uint16> arg0,
);

typedef _c_l64a = ffi.Pointer<ffi.Int8> Function(
  ffi.Int64 arg0,
);

typedef _dart_l64a = ffi.Pointer<ffi.Int8> Function(
  int arg0,
);

typedef _c_lcong48 = ffi.Void Function(
  ffi.Pointer<ffi.Uint16> arg0,
);

typedef _dart_lcong48 = void Function(
  ffi.Pointer<ffi.Uint16> arg0,
);

typedef _c_lrand48 = ffi.Int64 Function();

typedef _dart_lrand48 = int Function();

typedef _c_mktemp = ffi.Pointer<ffi.Int8> Function(
  ffi.Pointer<ffi.Int8> arg0,
);

typedef _dart_mktemp = ffi.Pointer<ffi.Int8> Function(
  ffi.Pointer<ffi.Int8> arg0,
);

typedef _c_mkstemp = ffi.Int32 Function(
  ffi.Pointer<ffi.Int8> arg0,
);

typedef _dart_mkstemp = int Function(
  ffi.Pointer<ffi.Int8> arg0,
);

typedef _c_mrand48 = ffi.Int64 Function();

typedef _dart_mrand48 = int Function();

typedef _c_nrand48 = ffi.Int64 Function(
  ffi.Pointer<ffi.Uint16> arg0,
);

typedef _dart_nrand48 = int Function(
  ffi.Pointer<ffi.Uint16> arg0,
);

typedef _c_posix_openpt = ffi.Int32 Function(
  ffi.Int32 arg0,
);

typedef _dart_posix_openpt = int Function(
  int arg0,
);

typedef _c_ptsname = ffi.Pointer<ffi.Int8> Function(
  ffi.Int32 arg0,
);

typedef _dart_ptsname = ffi.Pointer<ffi.Int8> Function(
  int arg0,
);

typedef _c_ptsname_r = ffi.Int32 Function(
  ffi.Int32 fildes,
  ffi.Pointer<ffi.Int8> buffer,
  ffi.Uint64 buflen,
);

typedef _dart_ptsname_r = int Function(
  int fildes,
  ffi.Pointer<ffi.Int8> buffer,
  int buflen,
);

typedef _c_putenv = ffi.Int32 Function(
  ffi.Pointer<ffi.Int8> arg0,
);

typedef _dart_putenv = int Function(
  ffi.Pointer<ffi.Int8> arg0,
);

typedef _c_random = ffi.Int64 Function();

typedef _dart_random = int Function();

typedef _c_rand_r = ffi.Int32 Function(
  ffi.Pointer<ffi.Uint32> arg0,
);

typedef _dart_rand_r = int Function(
  ffi.Pointer<ffi.Uint32> arg0,
);

typedef _c_realpath = ffi.Pointer<ffi.Int8> Function(
  ffi.Pointer<ffi.Int8> arg0,
  ffi.Pointer<ffi.Int8> arg1,
);

typedef _dart_realpath = ffi.Pointer<ffi.Int8> Function(
  ffi.Pointer<ffi.Int8> arg0,
  ffi.Pointer<ffi.Int8> arg1,
);

typedef _c_seed48 = ffi.Pointer<ffi.Uint16> Function(
  ffi.Pointer<ffi.Uint16> arg0,
);

typedef _dart_seed48 = ffi.Pointer<ffi.Uint16> Function(
  ffi.Pointer<ffi.Uint16> arg0,
);

typedef _c_setenv = ffi.Int32 Function(
  ffi.Pointer<ffi.Int8> __name,
  ffi.Pointer<ffi.Int8> __value,
  ffi.Int32 __overwrite,
);

typedef _dart_setenv = int Function(
  ffi.Pointer<ffi.Int8> __name,
  ffi.Pointer<ffi.Int8> __value,
  int __overwrite,
);

typedef _c_setkey = ffi.Void Function(
  ffi.Pointer<ffi.Int8> arg0,
);

typedef _dart_setkey = void Function(
  ffi.Pointer<ffi.Int8> arg0,
);

typedef _c_setstate = ffi.Pointer<ffi.Int8> Function(
  ffi.Pointer<ffi.Int8> arg0,
);

typedef _dart_setstate = ffi.Pointer<ffi.Int8> Function(
  ffi.Pointer<ffi.Int8> arg0,
);

typedef _c_srand48 = ffi.Void Function(
  ffi.Int64 arg0,
);

typedef _dart_srand48 = void Function(
  int arg0,
);

typedef _c_srandom = ffi.Void Function(
  ffi.Uint32 arg0,
);

typedef _dart_srandom = void Function(
  int arg0,
);

typedef _c_unlockpt = ffi.Int32 Function(
  ffi.Int32 arg0,
);

typedef _dart_unlockpt = int Function(
  int arg0,
);

typedef _c_unsetenv = ffi.Int32 Function(
  ffi.Pointer<ffi.Int8> arg0,
);

typedef _dart_unsetenv = int Function(
  ffi.Pointer<ffi.Int8> arg0,
);

typedef _c_arc4random = ffi.Uint32 Function();

typedef _dart_arc4random = int Function();

typedef _c_arc4random_addrandom = ffi.Void Function(
  ffi.Pointer<ffi.Uint8> arg0,
  ffi.Int32 arg1,
);

typedef _dart_arc4random_addrandom = void Function(
  ffi.Pointer<ffi.Uint8> arg0,
  int arg1,
);

typedef _c_arc4random_buf = ffi.Void Function(
  ffi.Pointer<ffi.Void> __buf,
  ffi.Uint64 __nbytes,
);

typedef _dart_arc4random_buf = void Function(
  ffi.Pointer<ffi.Void> __buf,
  int __nbytes,
);

typedef _c_arc4random_stir = ffi.Void Function();

typedef _dart_arc4random_stir = void Function();

typedef _c_arc4random_uniform = ffi.Uint32 Function(
  ffi.Uint32 __upper_bound,
);

typedef _dart_arc4random_uniform = int Function(
  int __upper_bound,
);

typedef _c_cgetcap = ffi.Pointer<ffi.Int8> Function(
  ffi.Pointer<ffi.Int8> arg0,
  ffi.Pointer<ffi.Int8> arg1,
  ffi.Int32 arg2,
);

typedef _dart_cgetcap = ffi.Pointer<ffi.Int8> Function(
  ffi.Pointer<ffi.Int8> arg0,
  ffi.Pointer<ffi.Int8> arg1,
  int arg2,
);

typedef _c_cgetclose = ffi.Int32 Function();

typedef _dart_cgetclose = int Function();

typedef _c_cgetent = ffi.Int32 Function(
  ffi.Pointer<ffi.Pointer<ffi.Int8>> arg0,
  ffi.Pointer<ffi.Pointer<ffi.Int8>> arg1,
  ffi.Pointer<ffi.Int8> arg2,
);

typedef _dart_cgetent = int Function(
  ffi.Pointer<ffi.Pointer<ffi.Int8>> arg0,
  ffi.Pointer<ffi.Pointer<ffi.Int8>> arg1,
  ffi.Pointer<ffi.Int8> arg2,
);

typedef _c_cgetfirst = ffi.Int32 Function(
  ffi.Pointer<ffi.Pointer<ffi.Int8>> arg0,
  ffi.Pointer<ffi.Pointer<ffi.Int8>> arg1,
);

typedef _dart_cgetfirst = int Function(
  ffi.Pointer<ffi.Pointer<ffi.Int8>> arg0,
  ffi.Pointer<ffi.Pointer<ffi.Int8>> arg1,
);

typedef _c_cgetmatch = ffi.Int32 Function(
  ffi.Pointer<ffi.Int8> arg0,
  ffi.Pointer<ffi.Int8> arg1,
);

typedef _dart_cgetmatch = int Function(
  ffi.Pointer<ffi.Int8> arg0,
  ffi.Pointer<ffi.Int8> arg1,
);

typedef _c_cgetnext = ffi.Int32 Function(
  ffi.Pointer<ffi.Pointer<ffi.Int8>> arg0,
  ffi.Pointer<ffi.Pointer<ffi.Int8>> arg1,
);

typedef _dart_cgetnext = int Function(
  ffi.Pointer<ffi.Pointer<ffi.Int8>> arg0,
  ffi.Pointer<ffi.Pointer<ffi.Int8>> arg1,
);

typedef _c_cgetnum = ffi.Int32 Function(
  ffi.Pointer<ffi.Int8> arg0,
  ffi.Pointer<ffi.Int8> arg1,
  ffi.Pointer<ffi.Int64> arg2,
);

typedef _dart_cgetnum = int Function(
  ffi.Pointer<ffi.Int8> arg0,
  ffi.Pointer<ffi.Int8> arg1,
  ffi.Pointer<ffi.Int64> arg2,
);

typedef _c_cgetset = ffi.Int32 Function(
  ffi.Pointer<ffi.Int8> arg0,
);

typedef _dart_cgetset = int Function(
  ffi.Pointer<ffi.Int8> arg0,
);

typedef _c_cgetstr = ffi.Int32 Function(
  ffi.Pointer<ffi.Int8> arg0,
  ffi.Pointer<ffi.Int8> arg1,
  ffi.Pointer<ffi.Pointer<ffi.Int8>> arg2,
);

typedef _dart_cgetstr = int Function(
  ffi.Pointer<ffi.Int8> arg0,
  ffi.Pointer<ffi.Int8> arg1,
  ffi.Pointer<ffi.Pointer<ffi.Int8>> arg2,
);

typedef _c_cgetustr = ffi.Int32 Function(
  ffi.Pointer<ffi.Int8> arg0,
  ffi.Pointer<ffi.Int8> arg1,
  ffi.Pointer<ffi.Pointer<ffi.Int8>> arg2,
);

typedef _dart_cgetustr = int Function(
  ffi.Pointer<ffi.Int8> arg0,
  ffi.Pointer<ffi.Int8> arg1,
  ffi.Pointer<ffi.Pointer<ffi.Int8>> arg2,
);

typedef _c_daemon = ffi.Int32 Function(
  ffi.Int32 arg0,
  ffi.Int32 arg1,
);

typedef _dart_daemon = int Function(
  int arg0,
  int arg1,
);

typedef _c_devname = ffi.Pointer<ffi.Int8> Function(
  ffi.Int32 arg0,
  ffi.Uint16 arg1,
);

typedef _dart_devname = ffi.Pointer<ffi.Int8> Function(
  int arg0,
  int arg1,
);

typedef _c_devname_r = ffi.Pointer<ffi.Int8> Function(
  ffi.Int32 arg0,
  ffi.Uint16 arg1,
  ffi.Pointer<ffi.Int8> buf,
  ffi.Int32 len,
);

typedef _dart_devname_r = ffi.Pointer<ffi.Int8> Function(
  int arg0,
  int arg1,
  ffi.Pointer<ffi.Int8> buf,
  int len,
);

typedef _c_getbsize = ffi.Pointer<ffi.Int8> Function(
  ffi.Pointer<ffi.Int32> arg0,
  ffi.Pointer<ffi.Int64> arg1,
);

typedef _dart_getbsize = ffi.Pointer<ffi.Int8> Function(
  ffi.Pointer<ffi.Int32> arg0,
  ffi.Pointer<ffi.Int64> arg1,
);

typedef _c_getloadavg = ffi.Int32 Function(
  ffi.Pointer<ffi.Double> arg0,
  ffi.Int32 arg1,
);

typedef _dart_getloadavg = int Function(
  ffi.Pointer<ffi.Double> arg0,
  int arg1,
);

typedef _c_getprogname = ffi.Pointer<ffi.Int8> Function();

typedef _dart_getprogname = ffi.Pointer<ffi.Int8> Function();

typedef _c_setprogname = ffi.Void Function(
  ffi.Pointer<ffi.Int8> arg0,
);

typedef _dart_setprogname = void Function(
  ffi.Pointer<ffi.Int8> arg0,
);

typedef _typedefC_10 = ffi.Int32 Function(
  ffi.Pointer<ffi.Void>,
  ffi.Pointer<ffi.Void>,
);

typedef _c_heapsort = ffi.Int32 Function(
  ffi.Pointer<ffi.Void> __base,
  ffi.Uint64 __nel,
  ffi.Uint64 __width,
  ffi.Pointer<ffi.NativeFunction<_typedefC_10>> __compar,
);

typedef _dart_heapsort = int Function(
  ffi.Pointer<ffi.Void> __base,
  int __nel,
  int __width,
  ffi.Pointer<ffi.NativeFunction<_typedefC_10>> __compar,
);

typedef _typedefC_11 = ffi.Int32 Function(
  ffi.Pointer<ffi.Void>,
  ffi.Pointer<ffi.Void>,
);

typedef _c_mergesort = ffi.Int32 Function(
  ffi.Pointer<ffi.Void> __base,
  ffi.Uint64 __nel,
  ffi.Uint64 __width,
  ffi.Pointer<ffi.NativeFunction<_typedefC_11>> __compar,
);

typedef _dart_mergesort = int Function(
  ffi.Pointer<ffi.Void> __base,
  int __nel,
  int __width,
  ffi.Pointer<ffi.NativeFunction<_typedefC_11>> __compar,
);

typedef _typedefC_12 = ffi.Int32 Function(
  ffi.Pointer<ffi.Void>,
  ffi.Pointer<ffi.Void>,
);

typedef _c_psort = ffi.Void Function(
  ffi.Pointer<ffi.Void> __base,
  ffi.Uint64 __nel,
  ffi.Uint64 __width,
  ffi.Pointer<ffi.NativeFunction<_typedefC_12>> __compar,
);

typedef _dart_psort = void Function(
  ffi.Pointer<ffi.Void> __base,
  int __nel,
  int __width,
  ffi.Pointer<ffi.NativeFunction<_typedefC_12>> __compar,
);

typedef _typedefC_13 = ffi.Int32 Function(
  ffi.Pointer<ffi.Void>,
  ffi.Pointer<ffi.Void>,
  ffi.Pointer<ffi.Void>,
);

typedef _c_psort_r = ffi.Void Function(
  ffi.Pointer<ffi.Void> __base,
  ffi.Uint64 __nel,
  ffi.Uint64 __width,
  ffi.Pointer<ffi.Void> arg3,
  ffi.Pointer<ffi.NativeFunction<_typedefC_13>> __compar,
);

typedef _dart_psort_r = void Function(
  ffi.Pointer<ffi.Void> __base,
  int __nel,
  int __width,
  ffi.Pointer<ffi.Void> arg3,
  ffi.Pointer<ffi.NativeFunction<_typedefC_13>> __compar,
);

typedef _typedefC_14 = ffi.Int32 Function(
  ffi.Pointer<ffi.Void>,
  ffi.Pointer<ffi.Void>,
  ffi.Pointer<ffi.Void>,
);

typedef _c_qsort_r = ffi.Void Function(
  ffi.Pointer<ffi.Void> __base,
  ffi.Uint64 __nel,
  ffi.Uint64 __width,
  ffi.Pointer<ffi.Void> arg3,
  ffi.Pointer<ffi.NativeFunction<_typedefC_14>> __compar,
);

typedef _dart_qsort_r = void Function(
  ffi.Pointer<ffi.Void> __base,
  int __nel,
  int __width,
  ffi.Pointer<ffi.Void> arg3,
  ffi.Pointer<ffi.NativeFunction<_typedefC_14>> __compar,
);

typedef _c_radixsort = ffi.Int32 Function(
  ffi.Pointer<ffi.Pointer<ffi.Uint8>> __base,
  ffi.Int32 __nel,
  ffi.Pointer<ffi.Uint8> __table,
  ffi.Uint32 __endbyte,
);

typedef _dart_radixsort = int Function(
  ffi.Pointer<ffi.Pointer<ffi.Uint8>> __base,
  int __nel,
  ffi.Pointer<ffi.Uint8> __table,
  int __endbyte,
);

typedef _c_rpmatch = ffi.Int32 Function(
  ffi.Pointer<ffi.Int8> arg0,
);

typedef _dart_rpmatch = int Function(
  ffi.Pointer<ffi.Int8> arg0,
);

typedef _c_sradixsort = ffi.Int32 Function(
  ffi.Pointer<ffi.Pointer<ffi.Uint8>> __base,
  ffi.Int32 __nel,
  ffi.Pointer<ffi.Uint8> __table,
  ffi.Uint32 __endbyte,
);

typedef _dart_sradixsort = int Function(
  ffi.Pointer<ffi.Pointer<ffi.Uint8>> __base,
  int __nel,
  ffi.Pointer<ffi.Uint8> __table,
  int __endbyte,
);

typedef _c_sranddev = ffi.Void Function();

typedef _dart_sranddev = void Function();

typedef _c_srandomdev = ffi.Void Function();

typedef _dart_srandomdev = void Function();

typedef _c_reallocf = ffi.Pointer<ffi.Void> Function(
  ffi.Pointer<ffi.Void> __ptr,
  ffi.Uint64 __size,
);

typedef _dart_reallocf = ffi.Pointer<ffi.Void> Function(
  ffi.Pointer<ffi.Void> __ptr,
  int __size,
);

typedef _c_strtoq = ffi.Int64 Function(
  ffi.Pointer<ffi.Int8> __str,
  ffi.Pointer<ffi.Pointer<ffi.Int8>> __endptr,
  ffi.Int32 __base,
);

typedef _dart_strtoq = int Function(
  ffi.Pointer<ffi.Int8> __str,
  ffi.Pointer<ffi.Pointer<ffi.Int8>> __endptr,
  int __base,
);

typedef _c_strtouq = ffi.Uint64 Function(
  ffi.Pointer<ffi.Int8> __str,
  ffi.Pointer<ffi.Pointer<ffi.Int8>> __endptr,
  ffi.Int32 __base,
);

typedef _dart_strtouq = int Function(
  ffi.Pointer<ffi.Int8> __str,
  ffi.Pointer<ffi.Pointer<ffi.Int8>> __endptr,
  int __base,
);

typedef _typedefC_1 = ffi.Void Function(
  ffi.Pointer<ffi.Void>,
);

typedef _typedefC_4 = ffi.Void Function(
  ffi.Int32,
);
