name: dart_pty
description: create pseudo terminal and fork process use dart
version: 0.0.3
author: Nightmare_MYS<906262255@qq.com>
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  ffi: ^1.0.0
  win32: ^2.0.0
  executorservices: ^2.0.3
  signale:
    git: https://github.com/Nightmare-MY/signale
