name: dart_pty
description: create pseudo terminal and fork process use dart
version: 0.0.3
author: Nightmare_MYS<906262255@qq.com>
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  ffi: ^0.1.3
  win32: ^1.6.10
  executorservices: ^2.0.3
