name: dart_pty
description: create pseudo terminal and fork process use dart
version: 0.0.3
author: Nightmare_MYS<906262255@qq.com>
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  ffi: ^1.0.0
  win32: ^2.1.0
  signale:
    git: https://github.com/nightmare-space/signale
